//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 15.06.2012 18:11:59
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace JoinTables
{

    /// <summary>
    /// There are no comments for JoinTables.Order, JoinTables in the schema.
    /// </summary>
    public partial class Order {

        private int _OrderID;

        private string _Company;

        private System.Nullable<double> _Price;

        private Iesi.Collections.Generic.ISet<OrderImplementer> _OrderImplementers;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Order()
        {
            this._OrderImplementers = new Iesi.Collections.Generic.HashedSet<OrderImplementer>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for OrderID in the schema.
        /// </summary>
        public virtual int OrderID
        {
            get
            {
                return this._OrderID;
            }
            set
            {
                this._OrderID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        public virtual string Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this._Company = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Price in the schema.
        /// </summary>
        public virtual System.Nullable<double> Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this._Price = value;
            }
        }

    
        /// <summary>
        /// There are no comments for OrderImplementers in the schema.
        /// </summary>
        public virtual Iesi.Collections.Generic.ISet<OrderImplementer> OrderImplementers
        {
            get
            {
                return this._OrderImplementers;
            }
            set
            {
                this._OrderImplementers = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for JoinTables.OrderImplementer, JoinTables in the schema.
    /// </summary>
    public partial class OrderImplementer {

        private int _ImplementerID;

        private string _Name;

        private Order _Order;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public OrderImplementer()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ImplementerID in the schema.
        /// </summary>
        public virtual int ImplementerID
        {
            get
            {
                return this._ImplementerID;
            }
            set
            {
                this._ImplementerID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        public virtual Order Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this._Order = value;
            }
        }
    }

}
