//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 12.06.2012 10:05:24
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ClassWithEnumTypeProperty
{

    /// <summary>
    /// There are no comments for ClassWithEnumTypeProperty.Employee, ClassWithEnumTypeProperty in the schema.
    /// </summary>
    public partial class Employee {

        private int _EmployeeID;

        private EmployeeType _EmployeeType;

        private string _FirstName;

        private string _LastName;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Employee()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for EmployeeID in the schema.
        /// </summary>
        public virtual int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this._EmployeeID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for EmployeeType in the schema.
        /// </summary>
        public virtual EmployeeType EmployeeType
        {
            get
            {
                return this._EmployeeType;
            }
            set
            {
                this._EmployeeType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for FirstName in the schema.
        /// </summary>
        public virtual string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this._FirstName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for LastName in the schema.
        /// </summary>
        public virtual string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this._LastName = value;
            }
        }
    }

}

namespace ClassWithEnumTypeProperty
{

    /// <summary>
    /// There are no comments for ClassWithEnumTypeProperty.EmployeeType, ClassWithEnumTypeProperty in the schema.
    /// </summary>
    public enum EmployeeType : int
 {
    
        /// <summary>
        /// There are no comments for EmployeeType.Manager in the schema.
        /// </summary>
        Manager = 1,    
        /// <summary>
        /// There are no comments for EmployeeType.Clerk in the schema.
        /// </summary>
        Clerk = 2,    
        /// <summary>
        /// There are no comments for EmployeeType.Courier in the schema.
        /// </summary>
        Courier = 3
    }

}
