//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21.06.2012 13:24:47
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ManyToMany
{

    /// <summary>
    /// There are no comments for ManyToMany.Shop, ManyToMany in the schema.
    /// </summary>
    public partial class Shop {

        private int _ShopID;

        private ContractorType _ShopDescription;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Shop()
        {
            this._ShopDescription = new ContractorType();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ShopID in the schema.
        /// </summary>
        public virtual int ShopID
        {
            get
            {
                return this._ShopID;
            }
            set
            {
                this._ShopID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ShopDescription in the schema.
        /// </summary>
        public virtual ContractorType ShopDescription
        {
            get
            {
                return this._ShopDescription;
            }
            set
            {
                this._ShopDescription = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for ManyToMany.Factory, ManyToMany in the schema.
    /// </summary>
    public partial class Factory {

        private int _FactoryID;

        private ContractorType _FactoryDescription;

        private System.Nullable<int> _WorkersCount;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Factory()
        {
            this._FactoryDescription = new ContractorType();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for FactoryID in the schema.
        /// </summary>
        public virtual int FactoryID
        {
            get
            {
                return this._FactoryID;
            }
            set
            {
                this._FactoryID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for FactoryDescription in the schema.
        /// </summary>
        public virtual ContractorType FactoryDescription
        {
            get
            {
                return this._FactoryDescription;
            }
            set
            {
                this._FactoryDescription = value;
            }
        }

    
        /// <summary>
        /// There are no comments for WorkersCount in the schema.
        /// </summary>
        public virtual System.Nullable<int> WorkersCount
        {
            get
            {
                return this._WorkersCount;
            }
            set
            {
                this._WorkersCount = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for ManyToMany.Company, ManyToMany in the schema.
    /// </summary>
    public partial class Company {

        private int _CompanyID;

        private string _CompanyName;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Company()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for CompanyID in the schema.
        /// </summary>
        public virtual int CompanyID
        {
            get
            {
                return this._CompanyID;
            }
            set
            {
                this._CompanyID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CompanyName in the schema.
        /// </summary>
        public virtual string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this._CompanyName = value;
            }
        }
    }

}

namespace ManyToMany
{

    /// <summary>
    /// There are no comments for ManyToMany.ContractorType, ManyToMany in the schema.
    /// </summary>
    public partial class ContractorType {

        private string _Name;

        private string _Address;

        private Iesi.Collections.Generic.ISet<Company> _Partners;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public ContractorType()
        {
            this._Partners = new Iesi.Collections.Generic.HashedSet<Company>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        public virtual string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Partners in the schema.
        /// </summary>
        public virtual Iesi.Collections.Generic.ISet<Company> Partners
        {
            get
            {
                return this._Partners;
            }
            set
            {
                this._Partners = value;
            }
        }
    }

}
