//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 13.06.2012 10:33:21
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace SimpleClassID
{

    /// <summary>
    /// There are no comments for SimpleClassID.Department, SimpleClassID in the schema.
    /// </summary>
    public partial class Department {

        private int _DEPTNO;

        private string _DNAME;

        private string _LOC;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Department()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for DEPTNO in the schema.
        /// </summary>
        public virtual int DEPTNO
        {
            get
            {
                return this._DEPTNO;
            }
            set
            {
                this._DEPTNO = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DNAME in the schema.
        /// </summary>
        public virtual string DNAME
        {
            get
            {
                return this._DNAME;
            }
            set
            {
                this._DNAME = value;
            }
        }

    
        /// <summary>
        /// There are no comments for LOC in the schema.
        /// </summary>
        public virtual string LOC
        {
            get
            {
                return this._LOC;
            }
            set
            {
                this._LOC = value;
            }
        }
    }

}
