//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 20.06.2012 15:22:11
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace IdBag
{

    /// <summary>
    /// There are no comments for IdBag.Factory, IdBag in the schema.
    /// </summary>
    public partial class Factory {

        private int _FactoryID;

        private string _FactoryName;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Factory()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for FactoryID in the schema.
        /// </summary>
        public virtual int FactoryID
        {
            get
            {
                return this._FactoryID;
            }
            set
            {
                this._FactoryID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for FactoryName in the schema.
        /// </summary>
        public virtual string FactoryName
        {
            get
            {
                return this._FactoryName;
            }
            set
            {
                this._FactoryName = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for IdBag.Company, IdBag in the schema.
    /// </summary>
    public partial class Company {

        private int _CompanyID;

        private string _CompanyName;

        private IList<Factory> _Factories;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Company()
        {
            this._Factories = new List<Factory>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for CompanyID in the schema.
        /// </summary>
        public virtual int CompanyID
        {
            get
            {
                return this._CompanyID;
            }
            set
            {
                this._CompanyID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CompanyName in the schema.
        /// </summary>
        public virtual string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this._CompanyName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Factories in the schema.
        /// </summary>
        public virtual IList<Factory> Factories
        {
            get
            {
                return this._Factories;
            }
            set
            {
                this._Factories = value;
            }
        }
    }

}
