//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 20.06.2012 17:58:58
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace TPT
{

    /// <summary>
    /// There are no comments for TPT.Snake, TPT in the schema.
    /// </summary>
    public partial class Snake : Animal {

        private System.Nullable<bool> _IsVenomous;

        private System.Nullable<decimal> _Length;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Snake()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for IsVenomous in the schema.
        /// </summary>
        public virtual System.Nullable<bool> IsVenomous
        {
            get
            {
                return this._IsVenomous;
            }
            set
            {
                this._IsVenomous = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Length in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Length
        {
            get
            {
                return this._Length;
            }
            set
            {
                this._Length = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for TPT.Horse, TPT in the schema.
    /// </summary>
    public partial class Horse : Animal {

        private string _Breed;

        private System.Nullable<decimal> _MaximumSpeed;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Horse()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Breed in the schema.
        /// </summary>
        public virtual string Breed
        {
            get
            {
                return this._Breed;
            }
            set
            {
                this._Breed = value;
            }
        }

    
        /// <summary>
        /// There are no comments for MaximumSpeed in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> MaximumSpeed
        {
            get
            {
                return this._MaximumSpeed;
            }
            set
            {
                this._MaximumSpeed = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for TPT.Dog, TPT in the schema.
    /// </summary>
    public partial class Dog : Animal {

        private string _Breed;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Dog()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Breed in the schema.
        /// </summary>
        public virtual string Breed
        {
            get
            {
                return this._Breed;
            }
            set
            {
                this._Breed = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for TPT.Crocodile, TPT in the schema.
    /// </summary>
    public partial class Crocodile : Animal {

        private System.Nullable<decimal> _Length;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Crocodile()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Length in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Length
        {
            get
            {
                return this._Length;
            }
            set
            {
                this._Length = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for TPT.Animal, TPT in the schema.
    /// </summary>
    public partial class Animal {

        private int _ID;

        private string _FoodClassification;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Animal()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ID in the schema.
        /// </summary>
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for FoodClassification in the schema.
        /// </summary>
        public virtual string FoodClassification
        {
            get
            {
                return this._FoodClassification;
            }
            set
            {
                this._FoodClassification = value;
            }
        }
    }

}
