//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 15.06.2012 12:41:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Array
{

    /// <summary>
    /// There are no comments for Array.Message, Array in the schema.
    /// </summary>
    public partial class Message {

        private int _Id;

        private string _Text;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Message()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Text in the schema.
        /// </summary>
        public virtual string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this._Text = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for Array.Conversation, Array in the schema.
    /// </summary>
    public partial class Conversation {

        private int _Id;

        private string _Description;

        private Message[] _Messages;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Conversation()
        {
            this._Messages = new Message[0];
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this._Description = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Messages in the schema.
        /// </summary>
        public virtual Message[] Messages
        {
            get
            {
                return this._Messages;
            }
            set
            {
                this._Messages = value;
            }
        }
    }

}
