//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22.06.2012 16:55:35
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ExecuteStoredFunction
{

    public partial class ModelMethodsExecutor
    {

        private NHibernate.ISession session;

        public ModelMethodsExecutor(NHibernate.ISession session)
        {
          this.session = session;
        }

    
        /// <summary>
        /// There are no comments for Sqrt in the schema.
        /// </summary>
        public System.Nullable<int> Sqrt(System.Nullable<int> param)
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"Sqrt");
            query.SetParameter(@"param", param);
            return ((System.Nullable<int>)(query.UniqueResult()));
        }

    
        /// <summary>
        /// There are no comments for Sqrt in the schema.
        /// </summary>
        public static System.Nullable<int> Sqrt(NHibernate.ISession session, System.Nullable<int> param)
        {

            NHibernate.IQuery query = session.GetNamedQuery(@"Sqrt");
            query.SetParameter(@"param", param);
            return ((System.Nullable<int>)(query.UniqueResult()));
        }
    }

}
