#pragma checksum "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\About.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A83FF12827E015F6C72A03A97D24DF9EA938A2C2"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using MyMVC;
    
    
    public class _Page_Views_Home_About_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_About_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\About.cshtml"
  
    ViewBag.Title = "About";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/About.cshtml", 35, 6, true);

WriteLiteral("\r\n<h2>");

EndContext("~/Views/Home/About.cshtml", 35, 6, true);

BeginContext("~/Views/Home/About.cshtml", 42, 13, false);

            
            #line 4 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\About.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 42, 13, false);

BeginContext("~/Views/Home/About.cshtml", 55, 12, true);

WriteLiteral(".</h2>\r\n<h3>");

EndContext("~/Views/Home/About.cshtml", 55, 12, true);

BeginContext("~/Views/Home/About.cshtml", 68, 15, false);

            
            #line 5 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\About.cshtml"
Write(ViewBag.Message);

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 68, 15, false);

BeginContext("~/Views/Home/About.cshtml", 83, 66, true);

WriteLiteral("</h3>\r\n\r\n<p>Use this area to provide additional information.</p>\r\n");

EndContext("~/Views/Home/About.cshtml", 83, 66, true);

        }
    }
}
