#pragma checksum "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "30C1A04A85F75767E4B547301DADBE0880E95833"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using MyMVC;
    
    
    public class _Page_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__Layout_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Shared/_Layout.cshtml", 0, 38, true);

WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n<meta");

EndContext("~/Views/Shared/_Layout.cshtml", 0, 38, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 38, 26, true);

WriteLiteral(" http-equiv=\"Content-Type\"");

EndContext("~/Views/Shared/_Layout.cshtml", 38, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 64, 35, true);

WriteLiteral(" content=\"text/html; charset=utf-8\"");

EndContext("~/Views/Shared/_Layout.cshtml", 64, 35, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 99, 13, true);

WriteLiteral("/>\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 99, 13, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 112, 16, true);

WriteLiteral(" charset=\"utf-8\"");

EndContext("~/Views/Shared/_Layout.cshtml", 112, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 128, 14, true);

WriteLiteral(" />\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 128, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 142, 16, true);

WriteLiteral(" name=\"viewport\"");

EndContext("~/Views/Shared/_Layout.cshtml", 142, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 158, 48, true);

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

EndContext("~/Views/Shared/_Layout.cshtml", 158, 48, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 206, 14, true);

WriteLiteral(">\r\n    <title>");

EndContext("~/Views/Shared/_Layout.cshtml", 206, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 221, 13, false);

            
            #line 7 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 221, 13, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 234, 28, true);

WriteLiteral(" - 我的 ASP.NET 应用程序</title>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 234, 28, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 262, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 262, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 267, 30, false);

            
            #line 8 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 267, 30, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 297, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 297, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 299, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 299, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 304, 37, false);

            
            #line 9 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 304, 37, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 341, 29, true);

WriteLiteral("\r\n\r\n</head>\r\n<body>\r\n    <div");

EndContext("~/Views/Shared/_Layout.cshtml", 341, 29, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 370, 47, true);

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

EndContext("~/Views/Shared/_Layout.cshtml", 370, 47, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 417, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Shared/_Layout.cshtml", 417, 15, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 432, 18, true);

WriteLiteral(" class=\"container\"");

EndContext("~/Views/Shared/_Layout.cshtml", 432, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 450, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 450, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 469, 22, true);

WriteLiteral(" class=\"navbar-header\"");

EndContext("~/Views/Shared/_Layout.cshtml", 469, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 491, 26, true);

WriteLiteral(">\r\n                <button");

EndContext("~/Views/Shared/_Layout.cshtml", 491, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 517, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Shared/_Layout.cshtml", 517, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 531, 22, true);

WriteLiteral(" class=\"navbar-toggle\"");

EndContext("~/Views/Shared/_Layout.cshtml", 531, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 553, 23, true);

WriteLiteral(" data-toggle=\"collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 553, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 576, 31, true);

WriteLiteral(" data-target=\".navbar-collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 576, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 607, 28, true);

WriteLiteral(">\r\n                    <span");

EndContext("~/Views/Shared/_Layout.cshtml", 607, 28, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 635, 17, true);

WriteLiteral(" class=\"icon-bar\"");

EndContext("~/Views/Shared/_Layout.cshtml", 635, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 652, 35, true);

WriteLiteral("></span>\r\n                    <span");

EndContext("~/Views/Shared/_Layout.cshtml", 652, 35, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 687, 17, true);

WriteLiteral(" class=\"icon-bar\"");

EndContext("~/Views/Shared/_Layout.cshtml", 687, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 704, 35, true);

WriteLiteral("></span>\r\n                    <span");

EndContext("~/Views/Shared/_Layout.cshtml", 704, 35, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 739, 17, true);

WriteLiteral(" class=\"icon-bar\"");

EndContext("~/Views/Shared/_Layout.cshtml", 739, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 756, 37, true);

WriteLiteral("></span>\r\n                </button>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 756, 37, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 793, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Shared/_Layout.cshtml", 793, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 810, 94, false);

            
            #line 21 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
           Write(Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 810, 94, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 904, 38, true);

WriteLiteral("\r\n            </div>\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 904, 38, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 942, 33, true);

WriteLiteral(" class=\"navbar-collapse collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 942, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 975, 22, true);

WriteLiteral(">\r\n                <ul");

EndContext("~/Views/Shared/_Layout.cshtml", 975, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 997, 23, true);

WriteLiteral(" class=\"nav navbar-nav\"");

EndContext("~/Views/Shared/_Layout.cshtml", 997, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1020, 27, true);

WriteLiteral(">\r\n                    <li>");

EndContext("~/Views/Shared/_Layout.cshtml", 1020, 27, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1048, 38, false);

            
            #line 25 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("主页", "Index", "Home"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1048, 38, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1086, 31, true);

WriteLiteral("</li>\r\n                    <li>");

EndContext("~/Views/Shared/_Layout.cshtml", 1086, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1118, 38, false);

            
            #line 26 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("关于", "About", "Home"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1118, 38, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1156, 31, true);

WriteLiteral("</li>\r\n                    <li>");

EndContext("~/Views/Shared/_Layout.cshtml", 1156, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1188, 42, false);

            
            #line 27 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("联系方式", "Contact", "Home"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1188, 42, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1230, 30, true);

WriteLiteral("</li>\r\n                </ul>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1230, 30, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1260, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Shared/_Layout.cshtml", 1260, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1277, 29, false);

            
            #line 29 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1277, 29, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1306, 58, true);

WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

EndContext("~/Views/Shared/_Layout.cshtml", 1306, 58, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1364, 31, true);

WriteLiteral(" class=\"container body-content\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1364, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1395, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1395, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1398, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Shared/_Layout.cshtml", 1398, 8, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1407, 12, false);

            
            #line 34 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1407, 12, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1419, 58, true);

WriteLiteral("\r\n        <hr />\r\n        <footer>\r\n            <p>&copy; ");

EndContext("~/Views/Shared/_Layout.cshtml", 1419, 58, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1478, 17, false);

            
            #line 37 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
                 Write(DateTime.Now.Year);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1478, 17, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1495, 57, true);

WriteLiteral(" - 我的 ASP.NET 应用程序</p>\r\n        </footer>\r\n    </div>\r\n\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1495, 57, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1552, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1552, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1557, 34, false);

            
            #line 41 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1557, 34, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1591, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1591, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1593, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1593, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1598, 37, false);

            
            #line 42 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1598, 37, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1635, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1635, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1637, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1637, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1642, 41, false);

            
            #line 43 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1642, 41, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1683, 20, true);

WriteLiteral("\r\n</body>\r\n</html>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1683, 20, true);

        }
    }
}
