#pragma checksum "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6D47C50F5CEA3BED88CA608694C46CB15752E225"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using MyMVC;
    
    #line 1 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Shared__LoginPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__LoginPartial_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml"
 if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
    
            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 198, 23, false);

            
            #line 6 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 198, 23, false);

            
            #line 6 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml"
                            


            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 225, 7, true);

WriteLiteral("    <ul");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 225, 7, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 232, 36, true);

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 232, 36, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 268, 17, true);

WriteLiteral(">\r\n        <li>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 268, 17, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 285, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 285, 12, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 298, 138, false);

            
            #line 10 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml"
       Write(Html.ActionLink("你好，" + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 298, 138, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 436, 31, true);

WriteLiteral("\r\n        </li>\r\n        <li><a");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 436, 31, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 467, 65, true);

WriteLiteral(" href=\"javascript:document.getElementById(\'logoutForm\').submit()\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 467, 65, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 532, 25, true);

WriteLiteral(">注销</a></li>\r\n    </ul>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 532, 25, true);

            
            #line 14 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml"
    }
}
else
{

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 576, 7, true);

WriteLiteral("    <ul");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 576, 7, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 583, 36, true);

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 583, 36, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 619, 15, true);

WriteLiteral(">\r\n        <li>");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 619, 15, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 635, 108, false);

            
            #line 19 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml"
       Write(Html.ActionLink("注册", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 635, 108, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 743, 19, true);

WriteLiteral("</li>\r\n        <li>");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 743, 19, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 763, 102, false);

            
            #line 20 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml"
       Write(Html.ActionLink("登录", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 763, 102, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 865, 18, true);

WriteLiteral("</li>\r\n    </ul>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 865, 18, true);

            
            #line 22 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\_LoginPartial.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
