#pragma checksum "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\Lockout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "90F30444F3E29C3D46C12741FCE4F1E011485856"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using MyMVC;
    
    
    public class _Page_Views_Shared_Lockout_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo> {
        
#line hidden
        
        public _Page_Views_Shared_Lockout_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\Lockout.cshtml"
  
    ViewBag.Title = "已锁定";

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/Lockout.cshtml", 74, 21, true);

WriteLiteral("\r\n\r\n<hgroup>\r\n    <h1");

EndContext("~/Views/Shared/Lockout.cshtml", 74, 21, true);

BeginContext("~/Views/Shared/Lockout.cshtml", 95, 20, true);

WriteLiteral(" class=\"text-danger\"");

EndContext("~/Views/Shared/Lockout.cshtml", 95, 20, true);

BeginContext("~/Views/Shared/Lockout.cshtml", 115, 19, true);

WriteLiteral(">已锁定。</h1>\r\n    <h2");

EndContext("~/Views/Shared/Lockout.cshtml", 115, 19, true);

BeginContext("~/Views/Shared/Lockout.cshtml", 134, 20, true);

WriteLiteral(" class=\"text-danger\"");

EndContext("~/Views/Shared/Lockout.cshtml", 134, 20, true);

BeginContext("~/Views/Shared/Lockout.cshtml", 154, 32, true);

WriteLiteral(">此帐户已锁定，请稍后重试。</h2>\r\n</hgroup>\r\n");

EndContext("~/Views/Shared/Lockout.cshtml", 154, 32, true);

        }
    }
}
