#pragma checksum "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\Contact.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "02CEAD01A3C380374CEE4D1CC063BD9175B86080"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using MyMVC;
    
    
    public class _Page_Views_Home_Contact_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_Contact_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\Contact.cshtml"
  
    ViewBag.Title = "Contact";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/Contact.cshtml", 37, 6, true);

WriteLiteral("\r\n<h2>");

EndContext("~/Views/Home/Contact.cshtml", 37, 6, true);

BeginContext("~/Views/Home/Contact.cshtml", 44, 13, false);

            
            #line 4 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\Contact.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Home/Contact.cshtml", 44, 13, false);

BeginContext("~/Views/Home/Contact.cshtml", 57, 12, true);

WriteLiteral(".</h2>\r\n<h3>");

EndContext("~/Views/Home/Contact.cshtml", 57, 12, true);

BeginContext("~/Views/Home/Contact.cshtml", 70, 15, false);

            
            #line 5 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\Contact.cshtml"
Write(ViewBag.Message);

            
            #line default
            #line hidden
EndContext("~/Views/Home/Contact.cshtml", 70, 15, false);

BeginContext("~/Views/Home/Contact.cshtml", 85, 92, true);

WriteLiteral("</h3>\r\n\r\n<address>\r\n    One Microsoft Way<br />\r\n    Redmond, WA 98052-6399<br />" +
"\r\n    <abbr");

EndContext("~/Views/Home/Contact.cshtml", 85, 92, true);

BeginContext("~/Views/Home/Contact.cshtml", 177, 14, true);

WriteLiteral(" title=\"Phone\"");

EndContext("~/Views/Home/Contact.cshtml", 177, 14, true);

BeginContext("~/Views/Home/Contact.cshtml", 191, 89, true);

WriteLiteral(">P:</abbr>\r\n    425.555.0100\r\n</address>\r\n\r\n<address>\r\n    <strong>Support:</stro" +
"ng>   <a");

EndContext("~/Views/Home/Contact.cshtml", 191, 89, true);

BeginContext("~/Views/Home/Contact.cshtml", 280, 34, true);

WriteLiteral(" href=\"mailto:Support@example.com\"");

EndContext("~/Views/Home/Contact.cshtml", 280, 34, true);

BeginContext("~/Views/Home/Contact.cshtml", 314, 66, true);

WriteLiteral(">Support@example.com</a><br />\r\n    <strong>Marketing:</strong> <a");

EndContext("~/Views/Home/Contact.cshtml", 314, 66, true);

BeginContext("~/Views/Home/Contact.cshtml", 380, 36, true);

WriteLiteral(" href=\"mailto:Marketing@example.com\"");

EndContext("~/Views/Home/Contact.cshtml", 380, 36, true);

BeginContext("~/Views/Home/Contact.cshtml", 416, 38, true);

WriteLiteral(">Marketing@example.com</a>\r\n</address>");

EndContext("~/Views/Home/Contact.cshtml", 416, 38, true);

        }
    }
}
