#pragma checksum "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\_ViewStart.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A4BC9CB4A1D11F0C28A746ED054B4CB82C25E233"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using MyMVC;
    
    
    public class _Page_Views__ViewStart_cshtml : System.Web.Mvc.ViewStartPage {
        
#line hidden
        
        public _Page_Views__ViewStart_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\_ViewStart.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
BeginContext("~/Views/_ViewStart.cshtml", 52, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/_ViewStart.cshtml", 52, 2, true);

        }
    }
}
