#pragma checksum "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\Error.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A6487ACBA77344855C46CC76FB80068C8467B4C5"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using MyMVC;
    
    
    public class _Page_Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo> {
        
#line hidden
        
        public _Page_Views_Shared_Error_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Shared\Error.cshtml"
  
    ViewBag.Title = "Error";

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/Error.cshtml", 76, 7, true);

WriteLiteral("\r\n\r\n<h1");

EndContext("~/Views/Shared/Error.cshtml", 76, 7, true);

BeginContext("~/Views/Shared/Error.cshtml", 83, 20, true);

WriteLiteral(" class=\"text-danger\"");

EndContext("~/Views/Shared/Error.cshtml", 83, 20, true);

BeginContext("~/Views/Shared/Error.cshtml", 103, 17, true);

WriteLiteral(">Error.</h1>\r\n<h2");

EndContext("~/Views/Shared/Error.cshtml", 103, 17, true);

BeginContext("~/Views/Shared/Error.cshtml", 120, 20, true);

WriteLiteral(" class=\"text-danger\"");

EndContext("~/Views/Shared/Error.cshtml", 120, 20, true);

BeginContext("~/Views/Shared/Error.cshtml", 140, 58, true);

WriteLiteral(">An error occurred while processing your request.</h2>\r\n\r\n");

EndContext("~/Views/Shared/Error.cshtml", 140, 58, true);

        }
    }
}
