#pragma checksum "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "27BCDFD17A7263B594DC633E8FC7765E924BEE5F"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using MyMVC;
    
    
    public class _Page_Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "c:\users\zhangyu\documents\visual studio 2015\Projects\MyMVC\MyMVC\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/Index.cshtml", 39, 8, true);

WriteLiteral("\r\n\r\n<div");

EndContext("~/Views/Home/Index.cshtml", 39, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 47, 18, true);

WriteLiteral(" class=\"jumbotron\"");

EndContext("~/Views/Home/Index.cshtml", 47, 18, true);

BeginContext("~/Views/Home/Index.cshtml", 65, 31, true);

WriteLiteral(">\r\n    <h1>ASP.NET</h1>\r\n    <p");

EndContext("~/Views/Home/Index.cshtml", 65, 31, true);

BeginContext("~/Views/Home/Index.cshtml", 96, 13, true);

WriteLiteral(" class=\"lead\"");

EndContext("~/Views/Home/Index.cshtml", 96, 13, true);

BeginContext("~/Views/Home/Index.cshtml", 109, 129, true);

WriteLiteral(">ASP.NET is a free web framework for building great Web sites and Web application" +
"s using HTML, CSS and JavaScript.</p>\r\n    <p><a");

EndContext("~/Views/Home/Index.cshtml", 109, 129, true);

BeginContext("~/Views/Home/Index.cshtml", 238, 22, true);

WriteLiteral(" href=\"http://asp.net\"");

EndContext("~/Views/Home/Index.cshtml", 238, 22, true);

BeginContext("~/Views/Home/Index.cshtml", 260, 31, true);

WriteLiteral(" class=\"btn btn-primary btn-lg\"");

EndContext("~/Views/Home/Index.cshtml", 260, 31, true);

BeginContext("~/Views/Home/Index.cshtml", 291, 43, true);

WriteLiteral(">Learn more &raquo;</a></p>\r\n</div>\r\n\r\n<div");

EndContext("~/Views/Home/Index.cshtml", 291, 43, true);

BeginContext("~/Views/Home/Index.cshtml", 334, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Home/Index.cshtml", 334, 12, true);

BeginContext("~/Views/Home/Index.cshtml", 346, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/Home/Index.cshtml", 346, 11, true);

BeginContext("~/Views/Home/Index.cshtml", 357, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/Index.cshtml", 357, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 374, 312, true);

WriteLiteral(@">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a");

EndContext("~/Views/Home/Index.cshtml", 374, 312, true);

BeginContext("~/Views/Home/Index.cshtml", 686, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Home/Index.cshtml", 686, 24, true);

BeginContext("~/Views/Home/Index.cshtml", 710, 53, true);

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=301865\"");

EndContext("~/Views/Home/Index.cshtml", 710, 53, true);

BeginContext("~/Views/Home/Index.cshtml", 763, 49, true);

WriteLiteral(">Learn more &raquo;</a></p>\r\n    </div>\r\n    <div");

EndContext("~/Views/Home/Index.cshtml", 763, 49, true);

BeginContext("~/Views/Home/Index.cshtml", 812, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/Index.cshtml", 812, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 829, 202, true);

WriteLiteral(">\r\n        <h2>Get more libraries</h2>\r\n        <p>NuGet is a free Visual Studio " +
"extension that makes it easy to add, remove, and update libraries and tools in V" +
"isual Studio projects.</p>\r\n        <p><a");

EndContext("~/Views/Home/Index.cshtml", 829, 202, true);

BeginContext("~/Views/Home/Index.cshtml", 1031, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Home/Index.cshtml", 1031, 24, true);

BeginContext("~/Views/Home/Index.cshtml", 1055, 53, true);

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=301866\"");

EndContext("~/Views/Home/Index.cshtml", 1055, 53, true);

BeginContext("~/Views/Home/Index.cshtml", 1108, 49, true);

WriteLiteral(">Learn more &raquo;</a></p>\r\n    </div>\r\n    <div");

EndContext("~/Views/Home/Index.cshtml", 1108, 49, true);

BeginContext("~/Views/Home/Index.cshtml", 1157, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/Index.cshtml", 1157, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 1174, 175, true);

WriteLiteral(">\r\n        <h2>Web Hosting</h2>\r\n        <p>You can easily find a web hosting com" +
"pany that offers the right mix of features and price for your applications.</p>\r" +
"\n        <p><a");

EndContext("~/Views/Home/Index.cshtml", 1174, 175, true);

BeginContext("~/Views/Home/Index.cshtml", 1349, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Home/Index.cshtml", 1349, 24, true);

BeginContext("~/Views/Home/Index.cshtml", 1373, 53, true);

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=301867\"");

EndContext("~/Views/Home/Index.cshtml", 1373, 53, true);

BeginContext("~/Views/Home/Index.cshtml", 1426, 47, true);

WriteLiteral(">Learn more &raquo;</a></p>\r\n    </div>\r\n</div>");

EndContext("~/Views/Home/Index.cshtml", 1426, 47, true);

        }
    }
}
