#pragma checksum "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "30943D98F72CBC89EEE413367A2015756AE3FE79"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using ServiceCenter.Client.Mvc;
    
    #line 2 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
    using ServiceCenter.Client.Mvc.Resources;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Account_Register_cshtml : System.Web.Mvc.WebViewPage<ServiceCenter.Client.Mvc.Models.RegisterViewModel> {
        
#line hidden
        
        public _Page_Views_Account_Register_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
  
    ViewBag.Title = StringResource.RegisterView_Title;

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 163, 8, true);

WriteLiteral("\r\n\r\n<h2>");

EndContext("~/Views/Account/Register.cshtml", 163, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 172, 13, false);

            
            #line 7 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 172, 13, false);

BeginContext("~/Views/Account/Register.cshtml", 185, 9, true);

WriteLiteral("</h2>\r\n\r\n");

EndContext("~/Views/Account/Register.cshtml", 185, 9, true);

            
            #line 9 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
 using (Html.BeginForm("Register", "Account",new { LoginName = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 356, 23, false);

            
            #line 11 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 356, 23, false);

            
            #line 11 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
                            

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 381, 8, true);

WriteLiteral("    <h4>");

EndContext("~/Views/Account/Register.cshtml", 381, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 390, 36, false);

            
            #line 12 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
   Write(StringResource.RegisterView_SubTitle);

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 390, 36, false);

BeginContext("~/Views/Account/Register.cshtml", 426, 7, true);

WriteLiteral("</h4>\r\n");

EndContext("~/Views/Account/Register.cshtml", 426, 7, true);

BeginContext("~/Views/Account/Register.cshtml", 433, 12, true);

WriteLiteral("    <hr />\r\n");

EndContext("~/Views/Account/Register.cshtml", 433, 12, true);

            
            #line 14 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 450, 28, false);

            
            #line 14 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 450, 28, false);

            
            #line 14 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
                                 

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 480, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 480, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 488, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Register.cshtml", 488, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 507, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 507, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 510, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 510, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 519, 74, false);

            
            #line 16 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
   Write(Html.LabelFor(m => m.LoginName, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 519, 74, false);

BeginContext("~/Views/Account/Register.cshtml", 593, 14, true);

WriteLiteral("\r\n        <div");

EndContext("~/Views/Account/Register.cshtml", 593, 14, true);

BeginContext("~/Views/Account/Register.cshtml", 607, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Account/Register.cshtml", 607, 17, true);

BeginContext("~/Views/Account/Register.cshtml", 624, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 624, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 627, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 627, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 640, 66, false);

            
            #line 18 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.TextBoxFor(m => m.LoginName, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 640, 66, false);

BeginContext("~/Views/Account/Register.cshtml", 706, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Register.cshtml", 706, 2, true);

BeginContext("~/Views/Account/Register.cshtml", 708, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 708, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 721, 43, false);

            
            #line 19 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.ValidationMessageFor(m => m.LoginName));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 721, 43, false);

BeginContext("~/Views/Account/Register.cshtml", 764, 30, true);

WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

EndContext("~/Views/Account/Register.cshtml", 764, 30, true);

BeginContext("~/Views/Account/Register.cshtml", 794, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 794, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 802, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Register.cshtml", 802, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 821, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 821, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 824, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 824, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 833, 73, false);

            
            #line 23 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
   Write(Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 833, 73, false);

BeginContext("~/Views/Account/Register.cshtml", 906, 14, true);

WriteLiteral("\r\n        <div");

EndContext("~/Views/Account/Register.cshtml", 906, 14, true);

BeginContext("~/Views/Account/Register.cshtml", 920, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Account/Register.cshtml", 920, 17, true);

BeginContext("~/Views/Account/Register.cshtml", 937, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 937, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 940, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 940, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 953, 65, false);

            
            #line 25 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.TextBoxFor(m => m.UserName, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 953, 65, false);

BeginContext("~/Views/Account/Register.cshtml", 1018, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Register.cshtml", 1018, 2, true);

BeginContext("~/Views/Account/Register.cshtml", 1020, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 1020, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 1033, 42, false);

            
            #line 26 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.ValidationMessageFor(m => m.UserName));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1033, 42, false);

BeginContext("~/Views/Account/Register.cshtml", 1075, 30, true);

WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

EndContext("~/Views/Account/Register.cshtml", 1075, 30, true);

BeginContext("~/Views/Account/Register.cshtml", 1105, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 1105, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 1113, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Register.cshtml", 1113, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 1132, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 1132, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 1135, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 1135, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 1144, 73, false);

            
            #line 30 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
   Write(Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1144, 73, false);

BeginContext("~/Views/Account/Register.cshtml", 1217, 14, true);

WriteLiteral("\r\n        <div");

EndContext("~/Views/Account/Register.cshtml", 1217, 14, true);

BeginContext("~/Views/Account/Register.cshtml", 1231, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Account/Register.cshtml", 1231, 17, true);

BeginContext("~/Views/Account/Register.cshtml", 1248, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 1248, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 1251, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 1251, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 1264, 66, false);

            
            #line 32 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.PasswordFor(m => m.Password, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1264, 66, false);

BeginContext("~/Views/Account/Register.cshtml", 1330, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Register.cshtml", 1330, 2, true);

BeginContext("~/Views/Account/Register.cshtml", 1332, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 1332, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 1345, 42, false);

            
            #line 33 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1345, 42, false);

BeginContext("~/Views/Account/Register.cshtml", 1387, 30, true);

WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

EndContext("~/Views/Account/Register.cshtml", 1387, 30, true);

BeginContext("~/Views/Account/Register.cshtml", 1417, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 1417, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 1425, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Register.cshtml", 1425, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 1444, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 1444, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 1447, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 1447, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 1456, 80, false);

            
            #line 37 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
   Write(Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1456, 80, false);

BeginContext("~/Views/Account/Register.cshtml", 1536, 14, true);

WriteLiteral("\r\n        <div");

EndContext("~/Views/Account/Register.cshtml", 1536, 14, true);

BeginContext("~/Views/Account/Register.cshtml", 1550, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Account/Register.cshtml", 1550, 17, true);

BeginContext("~/Views/Account/Register.cshtml", 1567, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 1567, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 1570, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 1570, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 1583, 73, false);

            
            #line 39 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1583, 73, false);

BeginContext("~/Views/Account/Register.cshtml", 1656, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Register.cshtml", 1656, 2, true);

BeginContext("~/Views/Account/Register.cshtml", 1658, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 1658, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 1671, 49, false);

            
            #line 40 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.ValidationMessageFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1671, 49, false);

BeginContext("~/Views/Account/Register.cshtml", 1720, 30, true);

WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

EndContext("~/Views/Account/Register.cshtml", 1720, 30, true);

BeginContext("~/Views/Account/Register.cshtml", 1750, 11, true);

WriteLiteral("    <hr/>\r\n");

EndContext("~/Views/Account/Register.cshtml", 1750, 11, true);

BeginContext("~/Views/Account/Register.cshtml", 1761, 7, true);

WriteLiteral("   <div");

EndContext("~/Views/Account/Register.cshtml", 1761, 7, true);

BeginContext("~/Views/Account/Register.cshtml", 1768, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Register.cshtml", 1768, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 1787, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 1787, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 1790, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 1790, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 1799, 70, false);

            
            #line 45 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
   Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1799, 70, false);

BeginContext("~/Views/Account/Register.cshtml", 1869, 14, true);

WriteLiteral("\r\n        <div");

EndContext("~/Views/Account/Register.cshtml", 1869, 14, true);

BeginContext("~/Views/Account/Register.cshtml", 1883, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Account/Register.cshtml", 1883, 17, true);

BeginContext("~/Views/Account/Register.cshtml", 1900, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 1900, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 1903, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 1903, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 1916, 63, false);

            
            #line 47 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.PasswordFor(m => m.Email, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1916, 63, false);

BeginContext("~/Views/Account/Register.cshtml", 1979, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Register.cshtml", 1979, 2, true);

BeginContext("~/Views/Account/Register.cshtml", 1981, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 1981, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 1994, 39, false);

            
            #line 48 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.ValidationMessageFor(m => m.Email));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1994, 39, false);

BeginContext("~/Views/Account/Register.cshtml", 2033, 30, true);

WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

EndContext("~/Views/Account/Register.cshtml", 2033, 30, true);

BeginContext("~/Views/Account/Register.cshtml", 2063, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 2063, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 2071, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Register.cshtml", 2071, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 2090, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 2090, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 2093, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 2093, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 2102, 76, false);

            
            #line 52 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
   Write(Html.LabelFor(m => m.OfficePhone, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 2102, 76, false);

BeginContext("~/Views/Account/Register.cshtml", 2178, 14, true);

WriteLiteral("\r\n        <div");

EndContext("~/Views/Account/Register.cshtml", 2178, 14, true);

BeginContext("~/Views/Account/Register.cshtml", 2192, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Account/Register.cshtml", 2192, 17, true);

BeginContext("~/Views/Account/Register.cshtml", 2209, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 2209, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 2212, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 2212, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 2225, 69, false);

            
            #line 54 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.PasswordFor(m => m.OfficePhone, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 2225, 69, false);

BeginContext("~/Views/Account/Register.cshtml", 2294, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Register.cshtml", 2294, 2, true);

BeginContext("~/Views/Account/Register.cshtml", 2296, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 2296, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 2309, 45, false);

            
            #line 55 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.ValidationMessageFor(m => m.OfficePhone));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 2309, 45, false);

BeginContext("~/Views/Account/Register.cshtml", 2354, 30, true);

WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

EndContext("~/Views/Account/Register.cshtml", 2354, 30, true);

BeginContext("~/Views/Account/Register.cshtml", 2384, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 2384, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 2392, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Register.cshtml", 2392, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 2411, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 2411, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 2414, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 2414, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 2423, 76, false);

            
            #line 59 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
   Write(Html.LabelFor(m => m.MobilePhone, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 2423, 76, false);

BeginContext("~/Views/Account/Register.cshtml", 2499, 14, true);

WriteLiteral("\r\n        <div");

EndContext("~/Views/Account/Register.cshtml", 2499, 14, true);

BeginContext("~/Views/Account/Register.cshtml", 2513, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Account/Register.cshtml", 2513, 17, true);

BeginContext("~/Views/Account/Register.cshtml", 2530, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Register.cshtml", 2530, 3, true);

BeginContext("~/Views/Account/Register.cshtml", 2533, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 2533, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 2546, 69, false);

            
            #line 61 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.PasswordFor(m => m.MobilePhone, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 2546, 69, false);

BeginContext("~/Views/Account/Register.cshtml", 2615, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Register.cshtml", 2615, 2, true);

BeginContext("~/Views/Account/Register.cshtml", 2617, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/Register.cshtml", 2617, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 2630, 45, false);

            
            #line 62 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
       Write(Html.ValidationMessageFor(m => m.MobilePhone));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 2630, 45, false);

BeginContext("~/Views/Account/Register.cshtml", 2675, 30, true);

WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

EndContext("~/Views/Account/Register.cshtml", 2675, 30, true);

BeginContext("~/Views/Account/Register.cshtml", 2705, 12, true);

WriteLiteral("     <hr/>\r\n");

EndContext("~/Views/Account/Register.cshtml", 2705, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 2717, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 2717, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 2725, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Register.cshtml", 2725, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 2744, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Account/Register.cshtml", 2744, 15, true);

BeginContext("~/Views/Account/Register.cshtml", 2759, 33, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-4\"");

EndContext("~/Views/Account/Register.cshtml", 2759, 33, true);

BeginContext("~/Views/Account/Register.cshtml", 2792, 21, true);

WriteLiteral(">\r\n            <input");

EndContext("~/Views/Account/Register.cshtml", 2792, 21, true);

BeginContext("~/Views/Account/Register.cshtml", 2813, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Account/Register.cshtml", 2813, 14, true);

BeginContext("~/Views/Account/Register.cshtml", 2827, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Account/Register.cshtml", 2827, 24, true);

WriteAttribute("value", Tuple.Create(" value=\"", 2851), Tuple.Create("\"", 2883)
            
            #line 68 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
, Tuple.Create(Tuple.Create("", 2859), Tuple.Create<System.Object, System.Int32>(StringResource.Register
            
            #line default
            #line hidden
, 2859), false)
);

BeginContext("~/Views/Account/Register.cshtml", 2884, 33, true);

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n");

EndContext("~/Views/Account/Register.cshtml", 2884, 33, true);

            
            #line 71 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Register.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
