//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_0dwfpnld {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_0dwfpnld() {
        }
        
        static object Create_ASP__Page_Views_Account_ModifyPassword_cshtml() {
            return new ASP._Page_Views_Account_ModifyPassword_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_Register_cshtml() {
            return new ASP._Page_Views_Account_Register_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_ModifyInfo_cshtml() {
            return new ASP._Page_Views_Account_ModifyInfo_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_Login_cshtml() {
            return new ASP._Page_Views_Account_Login_cshtml();
        }
    }
}
