//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_y3tuoejv {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_y3tuoejv() {
        }
        
        static object Create_ASP__Page_Views_Shared_Error_cshtml() {
            return new ASP._Page_Views_Shared_Error_cshtml();
        }
        
        static object Create_ASP__Page_Views_Shared__PaginationPartial_cshtml() {
            return new ASP._Page_Views_Shared__PaginationPartial_cshtml();
        }
        
        static object Create_ASP__Page_Views_Shared__LicensePartial_cshtml() {
            return new ASP._Page_Views_Shared__LicensePartial_cshtml();
        }
        
        static object Create_ASP__Page_Views_Shared__MenuPartial_cshtml() {
            return new ASP._Page_Views_Shared__MenuPartial_cshtml();
        }
        
        static object Create_ASP__Page_Views_Shared__LoginPartial_cshtml() {
            return new ASP._Page_Views_Shared__LoginPartial_cshtml();
        }
        
        static object Create_ASP__Page_Views_Shared_Unauthorized_cshtml() {
            return new ASP._Page_Views_Shared_Unauthorized_cshtml();
        }
        
        static object Create_ASP__Page_Views_Shared__Layout_cshtml() {
            return new ASP._Page_Views_Shared__Layout_cshtml();
        }
    }
}
