#pragma checksum "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0682DF6422F3FB40DB0A8804AF3C28D87C4A8D43"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using ServiceCenter.Client.Mvc;
    
    #line 1 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
    using ServiceCenter.Client.Mvc.Resources;
    
    #line default
    #line hidden
    
    #line 2 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Shared__LoginPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__LoginPartial_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
   
    string currentLanguage= "English";
    if (HttpContext.Current != null && HttpContext.Current.Session != null && HttpContext.Current.Session["Culture"] != null)
    {
        CultureInfo culture = (CultureInfo)HttpContext.Current.Session["Culture"];
        switch (culture.Name)
        {
            case "zh-CN":
                currentLanguage = "简";
                break;
            case "zh-TW":
                currentLanguage = "繁";
                break;
            case "en":
            default:
                currentLanguage = "EN";
                break;
        }
    }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 691, 5, true);

WriteLiteral("\r\n<ul");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 691, 5, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 696, 36, true);

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 696, 36, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 732, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 732, 3, true);

            
            #line 24 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
 if (Request.IsAuthenticated)
{
    using (Ajax.BeginForm("RedirectFunction", "Account",new { @Area = "" }, new AjaxOptions()
    {
        HttpMethod = "Post",
        OnBegin= "beginRedirectFunction",
        OnSuccess = "comleteRedirectFunction"
    }, htmlAttributes: new { @class = "navbar-form navbar-left form-inline" }))
    {

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1079, 12, true);

WriteLiteral("        <div");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1079, 12, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1091, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1091, 19, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1110, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1110, 19, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1129, 20, true);

WriteLiteral(" class=\"input-group\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1129, 20, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1149, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1149, 3, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1152, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1152, 16, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1169, 254, false);

            
            #line 35 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
           Write(Html.TextBox("functionCode", null, htmlAttributes: new { @class = "form-control", @data_val = "true", @data_val_required="", @placeholder = StringResource.Menu_FunctionCode, @style = "padding:2px;width:100px;text-transform:uppercase;ime-mode:disabled" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 1169, 254, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1423, 25, true);

WriteLiteral("\r\n                <button");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1423, 25, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1448, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1448, 14, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1462, 21, true);

WriteLiteral(" class=\"btn btn-info\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1462, 21, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1483, 50, true);

WriteLiteral(" style=\"border-radius:0px 4px 4px 0px;margin:-5px\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1483, 50, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1533, 50, true);

WriteLiteral(">Go</button>\r\n            </div>\r\n        </div>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1533, 50, true);

            
            #line 39 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
    }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1590, 10, true);

WriteLiteral("    <li>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1590, 10, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1600, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1600, 8, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1609, 180, false);

            
            #line 41 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
   Write(Html.ActionLink(StringResource.Hello + User.Identity.Name + "!", "ModifyPassword", "Account", routeValues: new { Area = "" }, htmlAttributes: new { title = StringResource.Manage }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 1609, 180, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1789, 13, true);

WriteLiteral("\r\n    </li>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1789, 13, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1802, 10, true);

WriteLiteral("    <li>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1802, 10, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1812, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1812, 8, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1821, 134, false);

            
            #line 44 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
   Write(Html.ActionLink(StringResource.Logout, "LogOff", "Account", routeValues: new { Area = "" }, htmlAttributes: new { id = "logoutLink" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 1821, 134, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1955, 13, true);

WriteLiteral("\r\n    </li>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1955, 13, true);

            
            #line 46 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
}
else
{

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1980, 8, true);

WriteLiteral("    <li>");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 1980, 8, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 1989, 140, false);

            
            #line 49 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
   Write(Html.ActionLink(StringResource.Register, "Register", "Account", routeValues: new { Area = "" }, htmlAttributes: new { id = "registerLink" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 1989, 140, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2129, 7, true);

WriteLiteral("</li>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2129, 7, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2136, 8, true);

WriteLiteral("    <li>");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2136, 8, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2145, 131, false);

            
            #line 50 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
   Write(Html.ActionLink(StringResource.Login, "Login", "Account", routeValues: new { Area = "" }, htmlAttributes: new { id = "loginLink" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 2145, 131, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2276, 7, true);

WriteLiteral("</li>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2276, 7, true);

            
            #line 51 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2286, 9, true);

WriteLiteral("\r\n    <li");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2286, 9, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2295, 17, true);

WriteLiteral(" class=\"dropdown\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2295, 17, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2312, 13, true);

WriteLiteral(">\r\n        <a");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2312, 13, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2325, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2325, 9, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2334, 38, true);

WriteLiteral(" class=\"dropdown-toggle panel-success\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2334, 38, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2372, 23, true);

WriteLiteral(" data-toggle=\"dropdown\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2372, 23, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2395, 14, true);

WriteLiteral(" role=\"button\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2395, 14, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2409, 21, true);

WriteLiteral(" aria-haspopup=\"true\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2409, 21, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2430, 22, true);

WriteLiteral(" aria-expanded=\"false\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2430, 22, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2452, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2452, 3, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2455, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2455, 16, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2472, 15, false);

            
            #line 55 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
           Write(currentLanguage);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 2472, 15, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2487, 6, true);

WriteLiteral(" <span");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2487, 6, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2493, 14, true);

WriteLiteral(" class=\"caret\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2493, 14, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2507, 35, true);

WriteLiteral("></span>\r\n        </a>\r\n        <ul");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2507, 35, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2542, 22, true);

WriteLiteral(" class=\"dropdown-menu\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2542, 22, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2564, 19, true);

WriteLiteral(">\r\n            <li>");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2564, 19, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2584, 121, false);

            
            #line 58 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
           Write(Html.ActionLink("简体中文", "SwitchLanuage", "Home", routeValues: new { Area = "", language ="zh-CN"},htmlAttributes:new { }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 2584, 121, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2705, 23, true);

WriteLiteral("</li>\r\n            <li>");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2705, 23, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2729, 125, false);

            
            #line 59 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
           Write(Html.ActionLink("繁体中文", "SwitchLanuage", "Home", routeValues: new { Area = "", language = "zh-TW" }, htmlAttributes: new { }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 2729, 125, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2854, 24, true);

WriteLiteral(" </li>\r\n            <li>");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 2854, 24, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 2879, 125, false);

            
            #line 60 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LoginPartial.cshtml"
           Write(Html.ActionLink("English", "SwitchLanuage", "Home", routeValues: new { Area = "", language = "en" }, htmlAttributes: new { }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 2879, 125, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 3004, 49, true);

WriteLiteral("</li>\r\n        </ul>\r\n    </li>\r\n</ul>\r\n\r\n<script");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 3004, 49, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 3053, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 3053, 23, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 3076, 22, true);

WriteLiteral(" language=\"javascript\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 3076, 22, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 3098, 632, true);

WriteLiteral(@">
    function beginRedirectFunction() {
    }

    function comleteRedirectFunction(result) {
        if (typeof (result) != undefined && result.Url != undefined && result.Url != """")
        {
            if (window.location != undefined
                && window.location != null
                && window.location.pathname != undefined
                && window.location.pathname != null
                && window.location.pathname.indexOf(result.Url)!=0)
            {
                window.location.replace(result.Url);
            }
        }
        $(""input[name='functionCode']"").val("""");
    }
</script>");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 3098, 632, true);

        }
    }
}
