#pragma checksum "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "16AEDDBC6F831C1301D3CCB775D56E31C174A191"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using ServiceCenter.Client.Mvc;
    
    #line 2 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
    using ServiceCenter.Client.Mvc.Resources;
    
    #line default
    #line hidden
    
    #line 3 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
    using log4net;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo> {
        
#line hidden
        
        public _Page_Views_Shared_Error_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 4 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
  
    ViewBag.Title = StringResource.ErrorPage_Title;
    if (Model != null)
    {
        string loggerName = string.Format("{0}/{1}", Model.ControllerName, Model.ActionName);
        ILog logger = LogManager.GetLogger(loggerName);
        logger.Error(Model.Exception);
    }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/Error.cshtml", 388, 15, true);

WriteLiteral("\r\n<p></p>\r\n<div");

EndContext("~/Views/Shared/Error.cshtml", 388, 15, true);

BeginContext("~/Views/Shared/Error.cshtml", 403, 27, true);

WriteLiteral(" class=\"panel panel-danger\"");

EndContext("~/Views/Shared/Error.cshtml", 403, 27, true);

BeginContext("~/Views/Shared/Error.cshtml", 430, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/Shared/Error.cshtml", 430, 11, true);

BeginContext("~/Views/Shared/Error.cshtml", 441, 22, true);

WriteLiteral(" class=\"panel-heading\"");

EndContext("~/Views/Shared/Error.cshtml", 441, 22, true);

BeginContext("~/Views/Shared/Error.cshtml", 463, 15, true);

WriteLiteral(">\r\n        <h4>");

EndContext("~/Views/Shared/Error.cshtml", 463, 15, true);

BeginContext("~/Views/Shared/Error.cshtml", 479, 13, false);

            
            #line 16 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
       Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Error.cshtml", 479, 13, false);

BeginContext("~/Views/Shared/Error.cshtml", 492, 27, true);

WriteLiteral("</h4>\r\n    </div>\r\n    <div");

EndContext("~/Views/Shared/Error.cshtml", 492, 27, true);

BeginContext("~/Views/Shared/Error.cshtml", 519, 19, true);

WriteLiteral(" class=\"panel-body\"");

EndContext("~/Views/Shared/Error.cshtml", 519, 19, true);

BeginContext("~/Views/Shared/Error.cshtml", 538, 14, true);

WriteLiteral(">\r\n        <h4");

EndContext("~/Views/Shared/Error.cshtml", 538, 14, true);

BeginContext("~/Views/Shared/Error.cshtml", 552, 20, true);

WriteLiteral(" class=\"text-danger\"");

EndContext("~/Views/Shared/Error.cshtml", 552, 20, true);

BeginContext("~/Views/Shared/Error.cshtml", 572, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/Error.cshtml", 572, 1, true);

BeginContext("~/Views/Shared/Error.cshtml", 574, 29, false);

            
            #line 19 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
                           Write(StringResource.ErrorPage_Text);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Error.cshtml", 574, 29, false);

BeginContext("~/Views/Shared/Error.cshtml", 603, 8, true);

WriteLiteral("。</h4>\r\n");

EndContext("~/Views/Shared/Error.cshtml", 603, 8, true);

            
            #line 20 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
        
            
            #line default
            #line hidden
            
            #line 20 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
         if (Model != null)
        {
            string message;
            if (Model.Exception.InnerException != null)
            {
                message = Model.Exception.InnerException.Message;
            }
            else
            {
                message = Model.Exception.Message;
            }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/Error.cshtml", 934, 11, true);

WriteLiteral("        <h4");

EndContext("~/Views/Shared/Error.cshtml", 934, 11, true);

BeginContext("~/Views/Shared/Error.cshtml", 945, 18, true);

WriteLiteral(" class=\"text-info\"");

EndContext("~/Views/Shared/Error.cshtml", 945, 18, true);

BeginContext("~/Views/Shared/Error.cshtml", 963, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/Error.cshtml", 963, 3, true);

BeginContext("~/Views/Shared/Error.cshtml", 966, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Shared/Error.cshtml", 966, 12, true);

BeginContext("~/Views/Shared/Error.cshtml", 979, 7, false);

            
            #line 32 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
       Write(message);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Error.cshtml", 979, 7, false);

BeginContext("~/Views/Shared/Error.cshtml", 986, 23, true);

WriteLiteral("<br />\r\n        </h4>\r\n");

EndContext("~/Views/Shared/Error.cshtml", 986, 23, true);

BeginContext("~/Views/Shared/Error.cshtml", 1009, 12, true);

WriteLiteral("        <div");

EndContext("~/Views/Shared/Error.cshtml", 1009, 12, true);

BeginContext("~/Views/Shared/Error.cshtml", 1021, 15, true);

WriteLiteral(" class=\"hidden\"");

EndContext("~/Views/Shared/Error.cshtml", 1021, 15, true);

BeginContext("~/Views/Shared/Error.cshtml", 1036, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/Error.cshtml", 1036, 3, true);

BeginContext("~/Views/Shared/Error.cshtml", 1039, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Shared/Error.cshtml", 1039, 12, true);

BeginContext("~/Views/Shared/Error.cshtml", 1052, 20, false);

            
            #line 35 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
       Write(Model.ControllerName);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Error.cshtml", 1052, 20, false);

BeginContext("~/Views/Shared/Error.cshtml", 1072, 1, true);

WriteLiteral("/");

EndContext("~/Views/Shared/Error.cshtml", 1072, 1, true);

BeginContext("~/Views/Shared/Error.cshtml", 1074, 16, false);

            
            #line 35 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
                             Write(Model.ActionName);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Error.cshtml", 1074, 16, false);

BeginContext("~/Views/Shared/Error.cshtml", 1090, 9, true);

WriteLiteral(" <br />\r\n");

EndContext("~/Views/Shared/Error.cshtml", 1090, 9, true);

BeginContext("~/Views/Shared/Error.cshtml", 1099, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Shared/Error.cshtml", 1099, 12, true);

BeginContext("~/Views/Shared/Error.cshtml", 1112, 26, false);

            
            #line 36 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
       Write(Model.Exception.ToString());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Error.cshtml", 1112, 26, false);

BeginContext("~/Views/Shared/Error.cshtml", 1138, 18, true);

WriteLiteral("\r\n        </div>\r\n");

EndContext("~/Views/Shared/Error.cshtml", 1138, 18, true);

            
            #line 38 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Error.cshtml"
        }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/Error.cshtml", 1167, 18, true);

WriteLiteral("    </div>\r\n</div>");

EndContext("~/Views/Shared/Error.cshtml", 1167, 18, true);

        }
    }
}
