#pragma checksum "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3078FCBCB1E2C587CC3D100E6FA9AFA1DC0F3F41"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using ServiceCenter.Client.Mvc;
    
    #line 2 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
    using ServiceCenter.Client.Mvc.Resources;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Account_Login_cshtml : System.Web.Mvc.WebViewPage<ServiceCenter.Client.Mvc.Models.LoginViewModel> {
        
#line hidden
        
        public _Page_Views_Account_Login_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
  
    ViewBag.Title = StringResource.LoginView_Title;

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Login.cshtml", 157, 8, true);

WriteLiteral("\r\n\r\n<h2>");

EndContext("~/Views/Account/Login.cshtml", 157, 8, true);

BeginContext("~/Views/Account/Login.cshtml", 166, 13, false);

            
            #line 7 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 166, 13, false);

BeginContext("~/Views/Account/Login.cshtml", 179, 11, true);

WriteLiteral("</h2>\r\n<div");

EndContext("~/Views/Account/Login.cshtml", 179, 11, true);

BeginContext("~/Views/Account/Login.cshtml", 190, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Account/Login.cshtml", 190, 12, true);

BeginContext("~/Views/Account/Login.cshtml", 202, 19, true);

WriteLiteral(" style=\"margin:0px\"");

EndContext("~/Views/Account/Login.cshtml", 202, 19, true);

BeginContext("~/Views/Account/Login.cshtml", 221, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/Account/Login.cshtml", 221, 11, true);

BeginContext("~/Views/Account/Login.cshtml", 232, 26, true);

WriteLiteral(" class=\"col-md-5 col-sm-5\"");

EndContext("~/Views/Account/Login.cshtml", 232, 26, true);

BeginContext("~/Views/Account/Login.cshtml", 258, 19, true);

WriteLiteral(">\r\n        <section");

EndContext("~/Views/Account/Login.cshtml", 258, 19, true);

BeginContext("~/Views/Account/Login.cshtml", 277, 15, true);

WriteLiteral(" id=\"loginForm\"");

EndContext("~/Views/Account/Login.cshtml", 277, 15, true);

BeginContext("~/Views/Account/Login.cshtml", 292, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Login.cshtml", 292, 3, true);

            
            #line 11 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
            
            
            #line default
            #line hidden
            
            #line 11 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
             using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                
            
            #line default
            #line hidden
BeginContext("~/Views/Account/Login.cshtml", 491, 23, false);

            
            #line 13 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 491, 23, false);

            
            #line 13 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                                        

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Login.cshtml", 516, 20, true);

WriteLiteral("                <h4>");

EndContext("~/Views/Account/Login.cshtml", 516, 20, true);

BeginContext("~/Views/Account/Login.cshtml", 537, 33, false);

            
            #line 14 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
               Write(StringResource.LoginView_SubTitle);

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 537, 33, false);

BeginContext("~/Views/Account/Login.cshtml", 570, 7, true);

WriteLiteral("</h4>\r\n");

EndContext("~/Views/Account/Login.cshtml", 570, 7, true);

BeginContext("~/Views/Account/Login.cshtml", 577, 24, true);

WriteLiteral("                <hr />\r\n");

EndContext("~/Views/Account/Login.cshtml", 577, 24, true);

            
            #line 16 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                
            
            #line default
            #line hidden
BeginContext("~/Views/Account/Login.cshtml", 618, 28, false);

            
            #line 16 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
           Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 618, 28, false);

            
            #line 16 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                                             

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Login.cshtml", 648, 20, true);

WriteLiteral("                <div");

EndContext("~/Views/Account/Login.cshtml", 648, 20, true);

BeginContext("~/Views/Account/Login.cshtml", 668, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Login.cshtml", 668, 19, true);

BeginContext("~/Views/Account/Login.cshtml", 687, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Login.cshtml", 687, 3, true);

BeginContext("~/Views/Account/Login.cshtml", 690, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/Login.cshtml", 690, 20, true);

BeginContext("~/Views/Account/Login.cshtml", 711, 82, false);

            
            #line 18 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
               Write(Html.LabelFor(m => m.UserName, new { @class = "col-md-2 col-sm-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 711, 82, false);

BeginContext("~/Views/Account/Login.cshtml", 793, 26, true);

WriteLiteral("\r\n                    <div");

EndContext("~/Views/Account/Login.cshtml", 793, 26, true);

BeginContext("~/Views/Account/Login.cshtml", 819, 26, true);

WriteLiteral(" class=\"col-md-9 col-sm-9\"");

EndContext("~/Views/Account/Login.cshtml", 819, 26, true);

BeginContext("~/Views/Account/Login.cshtml", 845, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Login.cshtml", 845, 3, true);

BeginContext("~/Views/Account/Login.cshtml", 848, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Account/Login.cshtml", 848, 24, true);

BeginContext("~/Views/Account/Login.cshtml", 873, 65, false);

            
            #line 20 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                   Write(Html.TextBoxFor(m => m.UserName, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 873, 65, false);

BeginContext("~/Views/Account/Login.cshtml", 938, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Login.cshtml", 938, 2, true);

BeginContext("~/Views/Account/Login.cshtml", 940, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Account/Login.cshtml", 940, 24, true);

BeginContext("~/Views/Account/Login.cshtml", 965, 42, false);

            
            #line 21 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                   Write(Html.ValidationMessageFor(m => m.UserName));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 965, 42, false);

BeginContext("~/Views/Account/Login.cshtml", 1007, 54, true);

WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

EndContext("~/Views/Account/Login.cshtml", 1007, 54, true);

BeginContext("~/Views/Account/Login.cshtml", 1061, 20, true);

WriteLiteral("                <div");

EndContext("~/Views/Account/Login.cshtml", 1061, 20, true);

BeginContext("~/Views/Account/Login.cshtml", 1081, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Login.cshtml", 1081, 19, true);

BeginContext("~/Views/Account/Login.cshtml", 1100, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Login.cshtml", 1100, 3, true);

BeginContext("~/Views/Account/Login.cshtml", 1103, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/Login.cshtml", 1103, 20, true);

BeginContext("~/Views/Account/Login.cshtml", 1124, 82, false);

            
            #line 25 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
               Write(Html.LabelFor(m => m.Password, new { @class = "col-md-2 col-sm-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 1124, 82, false);

BeginContext("~/Views/Account/Login.cshtml", 1206, 26, true);

WriteLiteral("\r\n                    <div");

EndContext("~/Views/Account/Login.cshtml", 1206, 26, true);

BeginContext("~/Views/Account/Login.cshtml", 1232, 26, true);

WriteLiteral(" class=\"col-md-9 col-sm-9\"");

EndContext("~/Views/Account/Login.cshtml", 1232, 26, true);

BeginContext("~/Views/Account/Login.cshtml", 1258, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Login.cshtml", 1258, 3, true);

BeginContext("~/Views/Account/Login.cshtml", 1261, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Account/Login.cshtml", 1261, 24, true);

BeginContext("~/Views/Account/Login.cshtml", 1286, 65, false);

            
            #line 27 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                   Write(Html.PasswordFor(m => m.Password, new { @class = "form-control"}));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 1286, 65, false);

BeginContext("~/Views/Account/Login.cshtml", 1351, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Login.cshtml", 1351, 2, true);

BeginContext("~/Views/Account/Login.cshtml", 1353, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Account/Login.cshtml", 1353, 24, true);

BeginContext("~/Views/Account/Login.cshtml", 1378, 42, false);

            
            #line 28 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 1378, 42, false);

BeginContext("~/Views/Account/Login.cshtml", 1420, 54, true);

WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

EndContext("~/Views/Account/Login.cshtml", 1420, 54, true);

BeginContext("~/Views/Account/Login.cshtml", 1474, 20, true);

WriteLiteral("                <div");

EndContext("~/Views/Account/Login.cshtml", 1474, 20, true);

BeginContext("~/Views/Account/Login.cshtml", 1494, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Login.cshtml", 1494, 19, true);

BeginContext("~/Views/Account/Login.cshtml", 1513, 27, true);

WriteLiteral(">\r\n                    <div");

EndContext("~/Views/Account/Login.cshtml", 1513, 27, true);

BeginContext("~/Views/Account/Login.cshtml", 1540, 58, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-9 col-sm-offset-2 col-sm-9\"");

EndContext("~/Views/Account/Login.cshtml", 1540, 58, true);

BeginContext("~/Views/Account/Login.cshtml", 1598, 31, true);

WriteLiteral(">\r\n                        <div");

EndContext("~/Views/Account/Login.cshtml", 1598, 31, true);

BeginContext("~/Views/Account/Login.cshtml", 1629, 17, true);

WriteLiteral(" class=\"checkbox\"");

EndContext("~/Views/Account/Login.cshtml", 1629, 17, true);

BeginContext("~/Views/Account/Login.cshtml", 1646, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Login.cshtml", 1646, 3, true);

BeginContext("~/Views/Account/Login.cshtml", 1649, 28, true);

WriteLiteral("                            ");

EndContext("~/Views/Account/Login.cshtml", 1649, 28, true);

BeginContext("~/Views/Account/Login.cshtml", 1678, 35, false);

            
            #line 34 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                       Write(Html.CheckBoxFor(m => m.RememberMe));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 1678, 35, false);

BeginContext("~/Views/Account/Login.cshtml", 1713, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Account/Login.cshtml", 1713, 2, true);

BeginContext("~/Views/Account/Login.cshtml", 1715, 28, true);

WriteLiteral("                            ");

EndContext("~/Views/Account/Login.cshtml", 1715, 28, true);

BeginContext("~/Views/Account/Login.cshtml", 1744, 32, false);

            
            #line 35 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                       Write(Html.LabelFor(m => m.RememberMe));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 1744, 32, false);

BeginContext("~/Views/Account/Login.cshtml", 1776, 86, true);

WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n");

EndContext("~/Views/Account/Login.cshtml", 1776, 86, true);

BeginContext("~/Views/Account/Login.cshtml", 1862, 20, true);

WriteLiteral("                <div");

EndContext("~/Views/Account/Login.cshtml", 1862, 20, true);

BeginContext("~/Views/Account/Login.cshtml", 1882, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/Login.cshtml", 1882, 19, true);

BeginContext("~/Views/Account/Login.cshtml", 1901, 27, true);

WriteLiteral(">\r\n                    <div");

EndContext("~/Views/Account/Login.cshtml", 1901, 27, true);

BeginContext("~/Views/Account/Login.cshtml", 1928, 60, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-10 col-sm-offset-2 col-sm-10\"");

EndContext("~/Views/Account/Login.cshtml", 1928, 60, true);

BeginContext("~/Views/Account/Login.cshtml", 1988, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Login.cshtml", 1988, 3, true);

BeginContext("~/Views/Account/Login.cshtml", 1991, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Account/Login.cshtml", 1991, 24, true);

BeginContext("~/Views/Account/Login.cshtml", 2016, 37, false);

            
            #line 41 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                   Write(StringResource.LoginView_RegisterInfo);

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 2016, 37, false);

BeginContext("~/Views/Account/Login.cshtml", 2053, 1, true);

WriteLiteral(" ");

EndContext("~/Views/Account/Login.cshtml", 2053, 1, true);

BeginContext("~/Views/Account/Login.cshtml", 2055, 62, false);

            
            #line 41 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
                                                          Write(Html.ActionLink(StringResource.LoginView_Register, "Register"));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 2055, 62, false);

BeginContext("~/Views/Account/Login.cshtml", 2117, 33, true);

WriteLiteral("，\r\n                        <input");

EndContext("~/Views/Account/Login.cshtml", 2117, 33, true);

BeginContext("~/Views/Account/Login.cshtml", 2150, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Account/Login.cshtml", 2150, 14, true);

WriteAttribute("value", Tuple.Create(" value=\"", 2164), Tuple.Create("\"", 2215)
            
            #line 42 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
, Tuple.Create(Tuple.Create(" ", 2172), Tuple.Create<System.Object, System.Int32>(StringResource.LoginView_LoginButtonText
            
            #line default
            #line hidden
, 2173), false)
, Tuple.Create(Tuple.Create(" ", 2214), Tuple.Create("", 2214), true)
);

BeginContext("~/Views/Account/Login.cshtml", 2216, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Account/Login.cshtml", 2216, 24, true);

BeginContext("~/Views/Account/Login.cshtml", 2240, 57, true);

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n");

EndContext("~/Views/Account/Login.cshtml", 2240, 57, true);

            
            #line 45 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
            }

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Login.cshtml", 2312, 40, true);

WriteLiteral("        </section>\r\n    </div>\r\n    <div");

EndContext("~/Views/Account/Login.cshtml", 2312, 40, true);

BeginContext("~/Views/Account/Login.cshtml", 2352, 36, true);

WriteLiteral(" class=\"col-md-7 col-sm-7 hidden-xs\"");

EndContext("~/Views/Account/Login.cshtml", 2352, 36, true);

BeginContext("~/Views/Account/Login.cshtml", 2388, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Account/Login.cshtml", 2388, 15, true);

BeginContext("~/Views/Account/Login.cshtml", 2403, 18, true);

WriteLiteral(" class=\"jumbotron\"");

EndContext("~/Views/Account/Login.cshtml", 2403, 18, true);

BeginContext("~/Views/Account/Login.cshtml", 2421, 19, true);

WriteLiteral(">\r\n            <h1>");

EndContext("~/Views/Account/Login.cshtml", 2421, 19, true);

BeginContext("~/Views/Account/Login.cshtml", 2441, 37, false);

            
            #line 50 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
           Write(StringResource.LoginView_WelcomeTitle);

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 2441, 37, false);

BeginContext("~/Views/Account/Login.cshtml", 2478, 21, true);

WriteLiteral("</h1>\r\n            <p");

EndContext("~/Views/Account/Login.cshtml", 2478, 21, true);

BeginContext("~/Views/Account/Login.cshtml", 2499, 13, true);

WriteLiteral(" class=\"lead\"");

EndContext("~/Views/Account/Login.cshtml", 2499, 13, true);

BeginContext("~/Views/Account/Login.cshtml", 2512, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/Login.cshtml", 2512, 3, true);

BeginContext("~/Views/Account/Login.cshtml", 2515, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Account/Login.cshtml", 2515, 16, true);

BeginContext("~/Views/Account/Login.cshtml", 2532, 39, false);

            
            #line 52 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\Login.cshtml"
           Write(StringResource.LoginView_WelcomeContent);

            
            #line default
            #line hidden
EndContext("~/Views/Account/Login.cshtml", 2532, 39, false);

BeginContext("~/Views/Account/Login.cshtml", 2571, 54, true);

WriteLiteral("\r\n            </p>\r\n        </div>\r\n    </div>\r\n</div>");

EndContext("~/Views/Account/Login.cshtml", 2571, 54, true);

        }
    }
}
