#pragma checksum "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4A7FEAAAB7B1F35EF83BD06818FBD200E698D891"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using ServiceCenter.Client.Mvc;
    
    #line 1 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
    using ServiceCenter.Client.Mvc.Models;
    
    #line default
    #line hidden
    
    #line 3 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
    using ServiceCenter.Client.Mvc.Resources;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Account_ModifyPassword_cshtml : System.Web.Mvc.WebViewPage<ServiceCenter.Client.Mvc.Models.ModifyPasswordViewModel> {
        
#line hidden
        
        public _Page_Views_Account_ModifyPassword_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 4 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
  
    ViewBag.Title = StringResource.ModifyPasswordView_Title;
    
    string clientName = HttpContext.Current.Request.UserHostName.Trim();
    string clientIP = HttpContext.Current.Request.UserHostAddress.Trim();
    string userAgent = HttpContext.Current.Request.UserAgent;

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyPassword.cshtml", 434, 8, true);

WriteLiteral("\r\n\r\n<h2>");

EndContext("~/Views/Account/ModifyPassword.cshtml", 434, 8, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 443, 13, false);

            
            #line 12 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 443, 13, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 456, 11, true);

WriteLiteral("</h2>\r\n\r\n<p");

EndContext("~/Views/Account/ModifyPassword.cshtml", 456, 11, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 467, 21, true);

WriteLiteral(" class=\"text-success\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 467, 21, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 488, 1, true);

WriteLiteral(">");

EndContext("~/Views/Account/ModifyPassword.cshtml", 488, 1, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 490, 21, false);

            
            #line 14 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
                   Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 490, 21, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 511, 10, true);

WriteLiteral("</p>\r\n<div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 511, 10, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 521, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 521, 12, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 533, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 533, 11, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 544, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 544, 18, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 562, 15, true);

WriteLiteral(">\r\n        <h4>");

EndContext("~/Views/Account/ModifyPassword.cshtml", 562, 15, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 578, 42, false);

            
            #line 17 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
       Write(StringResource.ModifyPasswordView_SubTitle);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 578, 42, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 620, 9, true);

WriteLiteral(" <strong>");

EndContext("~/Views/Account/ModifyPassword.cshtml", 620, 9, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 630, 18, false);

            
            #line 17 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
                                                           Write(User.Identity.Name);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 630, 18, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 648, 30, true);

WriteLiteral("</strong>。</h4>\r\n        <sub>");

EndContext("~/Views/Account/ModifyPassword.cshtml", 648, 30, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 679, 10, false);

            
            #line 18 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
        Write(clientName);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 679, 10, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 689, 21, true);

WriteLiteral("</sub>\r\n        <sub>");

EndContext("~/Views/Account/ModifyPassword.cshtml", 689, 21, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 711, 8, false);

            
            #line 19 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
        Write(clientIP);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 711, 8, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 719, 21, true);

WriteLiteral("</sub>\r\n        <sub>");

EndContext("~/Views/Account/ModifyPassword.cshtml", 719, 21, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 741, 9, false);

            
            #line 20 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
        Write(userAgent);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 741, 9, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 750, 8, true);

WriteLiteral("</sub>\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 750, 8, true);

            
            #line 21 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
        
            
            #line default
            #line hidden
            
            #line 21 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
         using (Html.BeginForm("ModifyPassword", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            
            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyPassword.cshtml", 912, 23, false);

            
            #line 23 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 912, 23, false);

            
            #line 23 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
                                    

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyPassword.cshtml", 937, 20, true);

WriteLiteral("            <hr />\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 937, 20, true);

            
            #line 25 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
            
            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyPassword.cshtml", 970, 24, false);

            
            #line 25 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 970, 24, false);

            
            #line 25 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
                                     

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyPassword.cshtml", 996, 16, true);

WriteLiteral("            <div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 996, 16, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1012, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1012, 19, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1031, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1031, 3, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1034, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1034, 16, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1051, 76, false);

            
            #line 27 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
           Write(Html.LabelFor(m => m.OldPassword, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 1051, 76, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1127, 22, true);

WriteLiteral("\r\n                <div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1127, 22, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1149, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1149, 18, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1167, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1167, 3, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1170, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1170, 20, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1191, 69, false);

            
            #line 29 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
               Write(Html.PasswordFor(m => m.OldPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 1191, 69, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1260, 46, true);

WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1260, 46, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1306, 16, true);

WriteLiteral("            <div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1306, 16, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1322, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1322, 19, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1341, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1341, 3, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1344, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1344, 16, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1361, 76, false);

            
            #line 33 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
           Write(Html.LabelFor(m => m.NewPassword, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 1361, 76, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1437, 22, true);

WriteLiteral("\r\n                <div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1437, 22, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1459, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1459, 18, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1477, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1477, 3, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1480, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1480, 20, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1501, 69, false);

            
            #line 35 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
               Write(Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 1501, 69, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1570, 46, true);

WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1570, 46, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1616, 16, true);

WriteLiteral("            <div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1616, 16, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1632, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1632, 19, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1651, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1651, 3, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1654, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1654, 16, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1671, 80, false);

            
            #line 39 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
           Write(Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 1671, 80, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1751, 22, true);

WriteLiteral("\r\n                <div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1751, 22, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1773, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1773, 18, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1791, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1791, 3, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1794, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1794, 20, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1815, 73, false);

            
            #line 41 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
               Write(Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 1815, 73, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1888, 46, true);

WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1888, 46, true);

            
            #line 44 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyPassword.cshtml", 1936, 16, true);

WriteLiteral("            <div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1936, 16, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1952, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1952, 19, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1971, 23, true);

WriteLiteral(">\r\n                <div");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1971, 23, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 1994, 34, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 1994, 34, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 2028, 29, true);

WriteLiteral(">\r\n                    <input");

EndContext("~/Views/Account/ModifyPassword.cshtml", 2028, 29, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 2057, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 2057, 14, true);

WriteAttribute("value", Tuple.Create(" value=\"", 2071), Tuple.Create("\"", 2128)
            
            #line 47 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
, Tuple.Create(Tuple.Create("", 2079), Tuple.Create<System.Object, System.Int32>(StringResource.ModifyPasswordView_ModifyPassword
            
            #line default
            #line hidden
, 2079), false)
);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 2129, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 2129, 24, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 2153, 81, true);

WriteLiteral(" />\r\n                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n" +
"");

EndContext("~/Views/Account/ModifyPassword.cshtml", 2153, 81, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 2234, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/ModifyPassword.cshtml", 2234, 20, true);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 2255, 173, false);

            
            #line 49 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
               Write(Html.ActionLink(StringResource.ModifyPasswordView_ModifyInfo, "ModifyInfo", "Account", routeValues: new { Area = "" }, htmlAttributes: new { title = StringResource.Manage }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyPassword.cshtml", 2255, 173, false);

BeginContext("~/Views/Account/ModifyPassword.cshtml", 2428, 46, true);

WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

EndContext("~/Views/Account/ModifyPassword.cshtml", 2428, 46, true);

            
            #line 52 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyPassword.cshtml"
        }

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyPassword.cshtml", 2485, 18, true);

WriteLiteral("    </div>\r\n</div>");

EndContext("~/Views/Account/ModifyPassword.cshtml", 2485, 18, true);

        }
    }
}
