#pragma checksum "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C339536E603ACEEF3B4EB2CAB246AFE079E20A56"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using ServiceCenter.Client.Mvc;
    
    #line 1 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
    using ServiceCenter.Client.Mvc.Models;
    
    #line default
    #line hidden
    
    #line 3 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
    using ServiceCenter.Client.Mvc.Resources;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Account_ModifyInfo_cshtml : System.Web.Mvc.WebViewPage<ServiceCenter.Client.Mvc.Models.ModifyInfoViewModel> {
        
#line hidden
        
        public _Page_Views_Account_ModifyInfo_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 4 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
  
    ViewBag.Title = StringResource.ModifyInfoView_Title;

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyInfo.cshtml", 208, 8, true);

WriteLiteral("\r\n\r\n<h2>");

EndContext("~/Views/Account/ModifyInfo.cshtml", 208, 8, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 217, 13, false);

            
            #line 8 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 217, 13, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 230, 11, true);

WriteLiteral("</h2>\r\n\r\n<p");

EndContext("~/Views/Account/ModifyInfo.cshtml", 230, 11, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 241, 21, true);

WriteLiteral(" class=\"text-success\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 241, 21, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 262, 1, true);

WriteLiteral(">");

EndContext("~/Views/Account/ModifyInfo.cshtml", 262, 1, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 264, 21, false);

            
            #line 10 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
                   Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 264, 21, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 285, 10, true);

WriteLiteral("</p>\r\n<div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 285, 10, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 295, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 295, 12, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 307, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 307, 11, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 318, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 318, 18, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 336, 15, true);

WriteLiteral(">\r\n        <h4>");

EndContext("~/Views/Account/ModifyInfo.cshtml", 336, 15, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 352, 38, false);

            
            #line 13 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
       Write(StringResource.ModifyInfoView_SubTitle);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 352, 38, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 390, 9, true);

WriteLiteral(" <strong>");

EndContext("~/Views/Account/ModifyInfo.cshtml", 390, 9, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 400, 18, false);

            
            #line 13 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
                                                       Write(User.Identity.Name);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 400, 18, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 418, 17, true);

WriteLiteral("</strong>。</h4>\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 418, 17, true);

            
            #line 14 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
        
            
            #line default
            #line hidden
            
            #line 14 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
         using (Html.BeginForm("ModifyInfo", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            
            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyInfo.cshtml", 585, 23, false);

            
            #line 16 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 585, 23, false);

            
            #line 16 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
                                    

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyInfo.cshtml", 610, 20, true);

WriteLiteral("            <hr />\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 610, 20, true);

            
            #line 18 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
            
            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyInfo.cshtml", 643, 24, false);

            
            #line 18 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 643, 24, false);

            
            #line 18 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
                                     

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyInfo.cshtml", 669, 16, true);

WriteLiteral("            <div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 669, 16, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 685, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 685, 19, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 704, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 704, 3, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 707, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Account/ModifyInfo.cshtml", 707, 16, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 724, 70, false);

            
            #line 20 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
           Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 724, 70, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 794, 22, true);

WriteLiteral("\r\n                <div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 794, 22, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 816, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 816, 18, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 834, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 834, 3, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 837, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/ModifyInfo.cshtml", 837, 20, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 858, 62, false);

            
            #line 22 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
               Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 858, 62, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 920, 46, true);

WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 920, 46, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 966, 16, true);

WriteLiteral("            <div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 966, 16, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 982, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 982, 19, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1001, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1001, 3, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1004, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1004, 16, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1021, 76, false);

            
            #line 26 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
           Write(Html.LabelFor(m => m.MobilePhone, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 1021, 76, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1097, 22, true);

WriteLiteral("\r\n                <div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1097, 22, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1119, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1119, 18, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1137, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1137, 3, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1140, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1140, 20, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1161, 68, false);

            
            #line 28 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
               Write(Html.TextBoxFor(m => m.MobilePhone, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 1161, 68, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1229, 46, true);

WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1229, 46, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1275, 16, true);

WriteLiteral("            <div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1275, 16, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1291, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1291, 19, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1310, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1310, 3, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1313, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1313, 16, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1330, 76, false);

            
            #line 32 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
           Write(Html.LabelFor(m => m.OfficePhone, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 1330, 76, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1406, 22, true);

WriteLiteral("\r\n                <div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1406, 22, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1428, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1428, 18, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1446, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1446, 3, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1449, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1449, 20, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1470, 68, false);

            
            #line 34 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
               Write(Html.TextBoxFor(m => m.OfficePhone, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 1470, 68, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1538, 46, true);

WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1538, 46, true);

            
            #line 37 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyInfo.cshtml", 1586, 16, true);

WriteLiteral("            <div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1586, 16, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1602, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1602, 19, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1621, 23, true);

WriteLiteral(">\r\n                <div");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1621, 23, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1644, 34, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1644, 34, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1678, 29, true);

WriteLiteral(">\r\n                    <input");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1678, 29, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1707, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1707, 14, true);

WriteAttribute("value", Tuple.Create(" value=\"", 1721), Tuple.Create("\"", 1770)
            
            #line 40 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
, Tuple.Create(Tuple.Create("", 1729), Tuple.Create<System.Object, System.Int32>(StringResource.ModifyInfoView_ModifyInfo
            
            #line default
            #line hidden
, 1729), false)
);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1771, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1771, 24, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1795, 69, true);

WriteLiteral(" />\r\n                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1795, 69, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1864, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Account/ModifyInfo.cshtml", 1864, 20, true);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 1885, 170, false);

            
            #line 42 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
               Write(Html.ActionLink(StringResource.ModifyPassword, "ModifyPassword", "Account", routeValues: new { Area = "" }, htmlAttributes: new { title = StringResource.ModifyPassword }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ModifyInfo.cshtml", 1885, 170, false);

BeginContext("~/Views/Account/ModifyInfo.cshtml", 2055, 46, true);

WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

EndContext("~/Views/Account/ModifyInfo.cshtml", 2055, 46, true);

            
            #line 45 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Account\ModifyInfo.cshtml"
        }

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ModifyInfo.cshtml", 2112, 18, true);

WriteLiteral("    </div>\r\n</div>");

EndContext("~/Views/Account/ModifyInfo.cshtml", 2112, 18, true);

        }
    }
}
