#pragma checksum "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "AADB5A0B63A6DA0DB1A3A3A4E3EF16354464FF30"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using ServiceCenter.Client.Mvc;
    
    #line 1 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
    using ServiceCenter.Client.Mvc.Resources;
    
    #line default
    #line hidden
    
    #line 2 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
    using ServiceCenter.Model;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Shared_Unauthorized_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared_Unauthorized_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
  
    ViewBag.Title = StringResource.Unauthorized_PageTitle;
    MethodReturnResult result=ViewBag.AuthenticateResult;

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/Unauthorized.cshtml", 197, 15, true);

WriteLiteral("\r\n<p></p>\r\n<div");

EndContext("~/Views/Shared/Unauthorized.cshtml", 197, 15, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 212, 27, true);

WriteLiteral(" class=\"panel panel-danger\"");

EndContext("~/Views/Shared/Unauthorized.cshtml", 212, 27, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 239, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/Shared/Unauthorized.cshtml", 239, 11, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 250, 22, true);

WriteLiteral(" class=\"panel-heading\"");

EndContext("~/Views/Shared/Unauthorized.cshtml", 250, 22, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 272, 14, true);

WriteLiteral(">\r\n        <h1");

EndContext("~/Views/Shared/Unauthorized.cshtml", 272, 14, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 286, 20, true);

WriteLiteral(" class=\"panel-title\"");

EndContext("~/Views/Shared/Unauthorized.cshtml", 286, 20, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 306, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/Unauthorized.cshtml", 306, 1, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 308, 13, false);

            
            #line 10 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
                           Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Unauthorized.cshtml", 308, 13, false);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 321, 27, true);

WriteLiteral("</h1>\r\n    </div>\r\n    <div");

EndContext("~/Views/Shared/Unauthorized.cshtml", 321, 27, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 348, 19, true);

WriteLiteral(" class=\"panel-body\"");

EndContext("~/Views/Shared/Unauthorized.cshtml", 348, 19, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 367, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/Unauthorized.cshtml", 367, 3, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 370, 7, true);

WriteLiteral("       ");

EndContext("~/Views/Shared/Unauthorized.cshtml", 370, 7, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 378, 32, false);

            
            #line 13 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
  Write(StringResource.Unauthorized_Code);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Unauthorized.cshtml", 378, 32, false);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 410, 2, true);

WriteLiteral("： ");

EndContext("~/Views/Shared/Unauthorized.cshtml", 410, 2, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 413, 11, false);

            
            #line 13 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
                                     Write(result.Code);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Unauthorized.cshtml", 413, 11, false);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 424, 8, true);

WriteLiteral("<br />\r\n");

EndContext("~/Views/Shared/Unauthorized.cshtml", 424, 8, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 432, 7, true);

WriteLiteral("       ");

EndContext("~/Views/Shared/Unauthorized.cshtml", 432, 7, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 440, 35, false);

            
            #line 14 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
  Write(StringResource.Unauthorized_Message);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Unauthorized.cshtml", 440, 35, false);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 475, 2, true);

WriteLiteral("： ");

EndContext("~/Views/Shared/Unauthorized.cshtml", 475, 2, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 478, 14, false);

            
            #line 14 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
                                        Write(result.Message);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Unauthorized.cshtml", 478, 14, false);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 492, 28, true);

WriteLiteral("<br />\r\n    </div>\r\n    <div");

EndContext("~/Views/Shared/Unauthorized.cshtml", 492, 28, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 520, 15, true);

WriteLiteral(" class=\"hidden\"");

EndContext("~/Views/Shared/Unauthorized.cshtml", 520, 15, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 535, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/Unauthorized.cshtml", 535, 3, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 538, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Shared/Unauthorized.cshtml", 538, 8, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 547, 34, false);

            
            #line 17 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
   Write(StringResource.Unauthorized_Detail);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Unauthorized.cshtml", 547, 34, false);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 581, 2, true);

WriteLiteral("： ");

EndContext("~/Views/Shared/Unauthorized.cshtml", 581, 2, true);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 584, 13, false);

            
            #line 17 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\Unauthorized.cshtml"
                                        Write(result.Detail);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/Unauthorized.cshtml", 584, 13, false);

BeginContext("~/Views/Shared/Unauthorized.cshtml", 597, 26, true);

WriteLiteral("<br />\r\n    </div>\r\n</div>");

EndContext("~/Views/Shared/Unauthorized.cshtml", 597, 26, true);

        }
    }
}
