#pragma checksum "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8690FF54F7813162F9B5ECA6065D57E218668CF2"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using ServiceCenter.Client.Mvc;
    
    #line 1 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
    using ServiceCenter.Client.Mvc.Resources;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__Layout_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Shared/_Layout.cshtml", 44, 42, true);

WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 44, 42, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 86, 26, true);

WriteLiteral(" http-equiv=\"Content-Type\"");

EndContext("~/Views/Shared/_Layout.cshtml", 86, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 112, 35, true);

WriteLiteral(" content=\"text/html; charset=utf-8\"");

EndContext("~/Views/Shared/_Layout.cshtml", 112, 35, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 147, 13, true);

WriteLiteral("/>\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 147, 13, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 160, 29, true);

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

EndContext("~/Views/Shared/_Layout.cshtml", 160, 29, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 189, 18, true);

WriteLiteral(" content=\"IE=edge\"");

EndContext("~/Views/Shared/_Layout.cshtml", 189, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 207, 12, true);

WriteLiteral(">\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 207, 12, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 219, 16, true);

WriteLiteral(" name=\"renderer\"");

EndContext("~/Views/Shared/_Layout.cshtml", 219, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 235, 17, true);

WriteLiteral(" content=\"webkit\"");

EndContext("~/Views/Shared/_Layout.cshtml", 235, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 252, 12, true);

WriteLiteral(">\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 252, 12, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 264, 16, true);

WriteLiteral(" charset=\"utf-8\"");

EndContext("~/Views/Shared/_Layout.cshtml", 264, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 280, 14, true);

WriteLiteral(" />\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 280, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 294, 16, true);

WriteLiteral(" name=\"viewport\"");

EndContext("~/Views/Shared/_Layout.cshtml", 294, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 310, 46, true);

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

EndContext("~/Views/Shared/_Layout.cshtml", 310, 46, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 356, 14, true);

WriteLiteral(">\r\n    <title>");

EndContext("~/Views/Shared/_Layout.cshtml", 356, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 371, 13, false);

            
            #line 10 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 371, 13, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 384, 3, true);

WriteLiteral(" - ");

EndContext("~/Views/Shared/_Layout.cshtml", 384, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 388, 24, false);

            
            #line 10 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
                       Write(StringResource.SiteTitle);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 388, 24, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 412, 10, true);

WriteLiteral("</title>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 412, 10, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 422, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 422, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 427, 30, false);

            
            #line 11 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 427, 30, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 457, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 457, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 459, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 459, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 464, 37, false);

            
            #line 12 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 464, 37, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 501, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 501, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 503, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 503, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 508, 40, false);

            
            #line 13 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(RenderSection("styles", required: false));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 508, 40, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 548, 27, true);

WriteLiteral("\r\n</head>\r\n<body>\r\n    <nav");

EndContext("~/Views/Shared/_Layout.cshtml", 548, 27, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 575, 48, true);

WriteLiteral(" class=\"navbar navbar-default navbar-static-top\"");

EndContext("~/Views/Shared/_Layout.cshtml", 575, 48, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 623, 18, true);

WriteLiteral(" role=\"navigation\"");

EndContext("~/Views/Shared/_Layout.cshtml", 623, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 641, 29, true);

WriteLiteral(" style=\"z-index:1;margin:0px\"");

EndContext("~/Views/Shared/_Layout.cshtml", 641, 29, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 670, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Shared/_Layout.cshtml", 670, 15, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 685, 24, true);

WriteLiteral(" class=\"container-fluid\"");

EndContext("~/Views/Shared/_Layout.cshtml", 685, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 709, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 709, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 728, 22, true);

WriteLiteral(" class=\"navbar-header\"");

EndContext("~/Views/Shared/_Layout.cshtml", 728, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 750, 20, true);

WriteLiteral(" style=\"padding:0px\"");

EndContext("~/Views/Shared/_Layout.cshtml", 750, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 770, 26, true);

WriteLiteral(">\r\n                <button");

EndContext("~/Views/Shared/_Layout.cshtml", 770, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 796, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Shared/_Layout.cshtml", 796, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 810, 22, true);

WriteLiteral(" class=\"navbar-toggle\"");

EndContext("~/Views/Shared/_Layout.cshtml", 810, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 832, 23, true);

WriteLiteral(" data-toggle=\"collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 832, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 855, 31, true);

WriteLiteral(" data-target=\".navbar-collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 855, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 886, 28, true);

WriteLiteral(">\r\n                    <span");

EndContext("~/Views/Shared/_Layout.cshtml", 886, 28, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 914, 17, true);

WriteLiteral(" class=\"icon-bar\"");

EndContext("~/Views/Shared/_Layout.cshtml", 914, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 931, 35, true);

WriteLiteral("></span>\r\n                    <span");

EndContext("~/Views/Shared/_Layout.cshtml", 931, 35, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 966, 17, true);

WriteLiteral(" class=\"icon-bar\"");

EndContext("~/Views/Shared/_Layout.cshtml", 966, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 983, 35, true);

WriteLiteral("></span>\r\n                    <span");

EndContext("~/Views/Shared/_Layout.cshtml", 983, 35, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1018, 17, true);

WriteLiteral(" class=\"icon-bar\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1018, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1035, 55, true);

WriteLiteral("></span>\r\n                </button>\r\n                <a");

EndContext("~/Views/Shared/_Layout.cshtml", 1035, 55, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1090, 21, true);

WriteLiteral(" class=\"navbar-brand\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1090, 21, true);

WriteAttribute("href", Tuple.Create(" href=\"", 1111), Tuple.Create("\"", 1164)
            
            #line 24 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1118), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home", new { area = "" })
            
            #line default
            #line hidden
, 1118), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 1165, 27, true);

WriteLiteral(">\r\n                    <img");

EndContext("~/Views/Shared/_Layout.cshtml", 1165, 27, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1192, 10, true);

WriteLiteral(" alt=\"MES\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1192, 10, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1202), Tuple.Create("\"", 1218)
, Tuple.Create(Tuple.Create("", 1208), Tuple.Create<System.Object, System.Int32>(Href("~/logo.png")
, 1208), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 1219, 12, true);

WriteLiteral(" height=\"20\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1219, 12, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1231, 61, true);

WriteLiteral(">\r\n                </a>\r\n            </div>\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 1231, 61, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1292, 33, true);

WriteLiteral(" class=\"navbar-collapse collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1292, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1325, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1325, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1328, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Shared/_Layout.cshtml", 1328, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1345, 81, false);

            
            #line 29 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("_MenuPartial", new ServiceCenter.Client.Mvc.Models.MenuViewModel()));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1345, 81, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1426, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1426, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1428, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Shared/_Layout.cshtml", 1428, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1445, 29, false);

            
            #line 30 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1445, 29, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1474, 50, true);

WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </nav>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1474, 50, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1524, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1524, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1529, 87, false);

            
            #line 34 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(Html.Partial("_LicensePartial", new ServiceCenter.Client.Mvc.Models.LicenseViewModel()));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1529, 87, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1616, 10, true);

WriteLiteral("\r\n    <div");

EndContext("~/Views/Shared/_Layout.cshtml", 1616, 10, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1626, 37, true);

WriteLiteral(" class=\"container-fluid body-content\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1626, 37, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1663, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1663, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1666, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Shared/_Layout.cshtml", 1666, 8, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1675, 12, false);

            
            #line 36 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1675, 12, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1687, 14, true);

WriteLiteral("\r\n    </div>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1687, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1701, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1701, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1706, 34, false);

            
            #line 38 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1706, 34, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1740, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1740, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1742, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1742, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1747, 37, false);

            
            #line 39 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery-ui"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1747, 37, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1784, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1784, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1786, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1786, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1791, 37, false);

            
            #line 40 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1791, 37, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1828, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1828, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1830, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1830, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1835, 45, false);

            
            #line 41 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jqueryunobtrusive"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1835, 45, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1880, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1880, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1882, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1882, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1887, 37, false);

            
            #line 42 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1887, 37, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1924, 13, true);

WriteLiteral("\r\n    <script");

EndContext("~/Views/Shared/_Layout.cshtml", 1924, 13, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1937, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1937, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1960, 1302, true);

WriteLiteral(@">
        $.datepicker.regional[""zh-CN""] = { closeText: ""关闭"", prevText: ""&#x3c;上月"", nextText: ""下月&#x3e;"", currentText: ""今天"", monthNames: [""一月"", ""二月"", ""三月"", ""四月"", ""五月"", ""六月"", ""七月"", ""八月"", ""九月"", ""十月"", ""十一月"", ""十二月""], monthNamesShort: [""一"", ""二"", ""三"", ""四"", ""五"", ""六"", ""七"", ""八"", ""九"", ""十"", ""十一"", ""十二""], dayNames: [""星期日"", ""星期一"", ""星期二"", ""星期三"", ""星期四"", ""星期五"", ""星期六""], dayNamesShort: [""周日"", ""周一"", ""周二"", ""周三"", ""周四"", ""周五"", ""周六""], dayNamesMin: [""日"", ""一"", ""二"", ""三"", ""四"", ""五"", ""六""], weekHeader: ""周"", dateFormat: ""yy-mm-dd"", firstDay: 1, isRTL: !1, showMonthAfterYear: !0, yearSuffix: ""年"" }
        $.timepicker.regional['zh-CN'] = {
            currentText: '当前',
            closeText: '完成',
            amNames: ['AM', 'A'],
            pmNames: ['PM', 'P'],
            timeFormat: 'HH:mm',
            timeSuffix: '',
            timeOnlyTitle: '选择时间',
            timeText: '时间',
            hourText: '小时',
            minuteText: '分钟',
            secondText: '秒数',
            millisecText: '毫秒',
            microsecText: '微秒',
            timezoneText: '时区',
            isRTL: false
        };
        $.datepicker.setDefaults($.datepicker.regional[""zh-CN""]);
        $.timepicker.setDefaults($.timepicker.regional['zh-CN']);

        $('[data-submenu]').submenupicker();
    </script>
");

EndContext("~/Views/Shared/_Layout.cshtml", 1960, 1302, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3262, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 3262, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3267, 41, false);

            
            #line 67 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 3267, 41, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 3308, 20, true);

WriteLiteral("\r\n</body>\r\n</html>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 3308, 20, true);

        }
    }
}
