#pragma checksum "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LicensePartial.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A65F6CD57F7EB7F1B5D55BEBFEE861F132E58E9D"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using ServiceCenter.Client.Mvc;
    
    #line 2 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LicensePartial.cshtml"
    using ServiceCenter.License;
    
    #line default
    #line hidden
    
    #line 3 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LicensePartial.cshtml"
    using ServiceCenter.Client.Mvc.Models;
    
    #line default
    #line hidden
    
    #line 4 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LicensePartial.cshtml"
    using ServiceCenter.Client.Mvc.Resources;
    
    #line default
    #line hidden
    
    #line 5 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LicensePartial.cshtml"
    using System.Text;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Shared__LicensePartial_cshtml : System.Web.Mvc.WebViewPage<ServiceCenter.Client.Mvc.Models.LicenseViewModel> {
        
#line hidden
        
        public _Page_Views_Shared__LicensePartial_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 6 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LicensePartial.cshtml"
   
    LicenseModel m = Model.GetCurrentLicenseModel();

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LicensePartial.cshtml", 254, 4, true);

WriteLiteral("\r\n\r\n");

EndContext("~/Views/Shared/_LicensePartial.cshtml", 254, 4, true);

            
            #line 10 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LicensePartial.cshtml"
 if (m != null && m.EndDate<DateTime.Now.Date)
{
    string message = string.Format(StringResource.License_Warning
                                   , (m.EndDate.Date - DateTime.Now.Date).Days + 16
                                   ,m.CompanyName);

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LicensePartial.cshtml", 514, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Shared/_LicensePartial.cshtml", 514, 8, true);

BeginContext("~/Views/Shared/_LicensePartial.cshtml", 522, 35, true);

WriteLiteral(" class=\"alert fade in alert-danger\"");

EndContext("~/Views/Shared/_LicensePartial.cshtml", 522, 35, true);

BeginContext("~/Views/Shared/_LicensePartial.cshtml", 557, 19, true);

WriteLiteral(" style=\"margin:0px\"");

EndContext("~/Views/Shared/_LicensePartial.cshtml", 557, 19, true);

BeginContext("~/Views/Shared/_LicensePartial.cshtml", 576, 15, true);

WriteLiteral(">\r\n        <p> ");

EndContext("~/Views/Shared/_LicensePartial.cshtml", 576, 15, true);

BeginContext("~/Views/Shared/_LicensePartial.cshtml", 592, 7, false);

            
            #line 16 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LicensePartial.cshtml"
       Write(message);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LicensePartial.cshtml", 592, 7, false);

BeginContext("~/Views/Shared/_LicensePartial.cshtml", 599, 19, true);

WriteLiteral(" </p>\r\n    </div>\r\n");

EndContext("~/Views/Shared/_LicensePartial.cshtml", 599, 19, true);

            
            #line 18 "D:\JC MES2.0\trunk\General\ServiceCenter.Client.Mvc\Views\Shared\_LicensePartial.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
