//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 19.06.2012 9:45:19
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace UniqueKeys
{

    /// <summary>
    /// There are no comments for UniqueKeys.Factory, UniqueKeys in the schema.
    /// </summary>
    public partial class Factory {

        private int _FactoryID;

        private string _FactoryName;

        private Iesi.Collections.Generic.ISet<Company> _Companies;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Factory()
        {
            this._Companies = new Iesi.Collections.Generic.HashedSet<Company>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for FactoryID in the schema.
        /// </summary>
        public virtual int FactoryID
        {
            get
            {
                return this._FactoryID;
            }
            set
            {
                this._FactoryID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for FactoryName in the schema.
        /// </summary>
        public virtual string FactoryName
        {
            get
            {
                return this._FactoryName;
            }
            set
            {
                this._FactoryName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Companies in the schema.
        /// </summary>
        public virtual Iesi.Collections.Generic.ISet<Company> Companies
        {
            get
            {
                return this._Companies;
            }
            set
            {
                this._Companies = value;
            }
        }
    }

    /// <summary>
    /// There are no comments for UniqueKeys.Company, UniqueKeys in the schema.
    /// </summary>
    public partial class Company {

        private int _CompanyID;

        private string _CompanyName;

        private Iesi.Collections.Generic.ISet<Factory> _Factories;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Company()
        {
            this._Factories = new Iesi.Collections.Generic.HashedSet<Factory>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for CompanyID in the schema.
        /// </summary>
        public virtual int CompanyID
        {
            get
            {
                return this._CompanyID;
            }
            set
            {
                this._CompanyID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CompanyName in the schema.
        /// </summary>
        public virtual string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this._CompanyName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Factories in the schema.
        /// </summary>
        public virtual Iesi.Collections.Generic.ISet<Factory> Factories
        {
            get
            {
                return this._Factories;
            }
            set
            {
                this._Factories = value;
            }
        }
    }

}
